// srcs/services/frontend/src/App.tsx
import { useState, useEffect } from 'react'
import { PongGame } from './components/PongGame'
import { MultiplayerPong } from './components/MultiPlayerPong'
import { AIPong } from './components/AIPong'
import { LoginForm } from './components/LoginForm'
import { RegisterForm } from './components/RegisterForm'
import { UserProfile } from './components/UserProfile'
import { ForgotUsername } from './components/ForgotUsername'
import { ForgotPassword } from './components/ForgotPassword'
import { DeleteAccountPage } from './components/DeleteAccountPage'
import { GameSettings } from './components/GameSettings'
import { AuthService } from './services/authService'
import { AuthResponse, User } from './types/auth'
import { GameSettingsProvider } from './contexts/GameSettingsContext'
import Ranking from './components/Ranking';

/**
 * Main App Component
 */
function App() {
  const [gameMode, setGameMode] = useState<'menu' | 'single' | 'multiplayer' | 'ai'>('menu');
  
    // NOTE: roomId and playerSide are now ONLY for the multiplayer mode.
  const [roomId, setRoomId] = useState('');
  const [playerSide, setPlayerSide] = useState<'left' | 'right'>('left');

  // Authentication state
  const [user, setUser] = useState<User | null>(null);
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [authMode, setAuthMode] = useState<'login' | 'register'>('login');
  const [view, setView] = useState<'game' | 'profile' | 'deleteAccount' | 'forgotPassword' | 'forgotUsername' | 'settings' | 'ranking'>('game');
  const [showSettings, setShowSettings] = useState(false);

  /**
   * Check authentication status on component mount
   */
  useEffect(() => {
    const checkAuth = () => {
      try {
        const storedAuth = AuthService.getStoredAuthData();
        if (storedAuth && AuthService.isAuthenticated()) {
          setUser(storedAuth.user);
          setIsAuthenticated(true);
        } else {
          // Clear invalid auth data
          AuthService.clearAuthData();
          setUser(null);
          setIsAuthenticated(false);
        }
      } catch (error) {
        console.error('Error checking authentication:', error);
        AuthService.clearAuthData();
        setUser(null);
        setIsAuthenticated(false);
      }
      setIsLoading(false);
    };

    checkAuth();
  }, []);

  /**
   * Handle successful authentication
   */
  const handleAuthSuccess = (authData: AuthResponse) => {
    setUser(authData.user);
    setIsAuthenticated(true);
    setView('game');
  };

  /**
   * Handle logout
   */
  const handleLogout = () => {
    setUser(null);
    setIsAuthenticated(false);
    setAuthMode('login');
    setView('game');
    AuthService.clearAuthData();
  };

  // --- (NEW) --- A simple function to start the local 2-player game.
  const startSinglePlayerGame = () => {
    setGameMode('single');
  };
  
  // --- (NEW) --- A simple function to show the multiplayer setup screen.
  const showMultiplayerSetup = () => {
    setGameMode('multiplayer');
  };

  // --- (NEW) --- A simple function to start the AI game.
  const startAIGame = () => {
    setGameMode('ai');
  };

  // --- (NEW) --- A simple function to return to menu.
  const handleReturnToMenu = () => {
    setGameMode('menu');
  };


  // --- (CHANGED) --- Render logic is updated for clarity and correctness.
  const renderGameContent = () => {
    switch(gameMode) {
      case 'single':
        return (
          <>
            <PongGame />
            <button 
              onClick={handleReturnToMenu}
              className="mt-4 px-4 py-2 bg-gray-600 rounded hover:bg-gray-700"
            >
              Back to Menu
            </button>
          </>
        );

      case 'multiplayer':
        return (
          <>
            <div className="mb-4">
              <input
                type="text"
                placeholder="Enter Room ID to Join/Create"
                value={roomId}
                onChange={(e) => setRoomId(e.target.value)}
                className="px-4 py-2 text-black rounded mr-2"
              />
              <select
                value={playerSide}
                onChange={(e) => setPlayerSide(e.target.value as 'left' | 'right')}
                className="px-4 py-2 text-black rounded"
              >
                <option value="left">Left Player</option>
                <option value="right">Right Player</option>
              </select>
            </div>
            
            {/* The actual multiplayer game, which DOES require a roomId */}
            {roomId && (
              <MultiplayerPong roomId={roomId} playerSide={playerSide} />
            )}
            
            <button 
              onClick={handleReturnToMenu}
              className="mt-4 px-4 py-2 bg-gray-600 rounded hover:bg-gray-700"
            >
              Back to Menu
            </button>
          </>
        );
        
      case 'ai':
        return (
          <>
            {/* --- (CHANGED) --- Render AIPong directly, without checking for or passing a roomId */}
            <AIPong />
            <button 
              onClick={handleReturnToMenu}
              className="mt-4 px-4 py-2 bg-gray-600 rounded hover:bg-gray-700"
            >
              Back to Menu
            </button>
          </>
        );

      case 'menu':
      default:
        return (
          <div className="space-y-4 flex flex-col items-center">
            <button 
              onClick={startSinglePlayerGame}
              className="px-6 py-3 bg-indigo-600 rounded hover:bg-indigo-700 w-64 text-lg"
            >
              Player vs Player (Local)
            </button>
            <button 
              onClick={showMultiplayerSetup}
              className="px-6 py-3 bg-blue-600 rounded hover:bg-blue-700 w-64 text-lg"
            >
              Multiplayer (Online)
            </button>
            <button 
              onClick={startAIGame}
              className="px-6 py-3 bg-green-600 rounded hover:bg-green-700 w-64 text-lg"
            >
              Player vs AI
            </button>
            <button 
              onClick={() => setShowSettings(true)}
              className="px-6 py-3 bg-purple-600 rounded hover:bg-purple-700 w-64 text-lg"
            >
              Game Settings
            </button>
            <button 
              onClick={() => setView('ranking')}
              className="px-6 py-3 bg-yellow-600 rounded hover:bg-yellow-700 w-64 text-lg"
            >
              Ranking
            </button>
          </div>
        );
    }
  };


  // Show loading screen while checking authentication
  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-900 text-white flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-4xl mb-8">Transcendence Pong</h1>
          <p>Loading...</p>
        </div>
      </div>
    );
  }

  // Show authentication forms if not authenticated
  if (!isAuthenticated) {
    return (
      <div className="min-h-screen bg-gray-900 text-white flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-4xl mb-8">Transcendence Pong</h1>
          <p className="text-gray-400 mb-8">Please sign in to play the game</p>
          {authMode === 'login' ? (
            <LoginForm 
              onLoginSuccess={handleAuthSuccess}
              onSwitchToRegister={() => setAuthMode('register')}
              onSwitchToForgotPassword={() => setView('forgotPassword')}
              onSwitchToForgotUsername={() => setView('forgotUsername')}
            />
          ) : (
            <RegisterForm 
              onRegisterSuccess={handleAuthSuccess}
              onSwitchToLogin={() => setAuthMode('login')}
            />
          )}
        </div>
      </div>
    );
  }

  // Show different views based on current view state
  if (view === 'profile') {
    return (
      <div className="min-h-screen bg-gray-900 text-white flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-4xl mb-8">User Profile</h1>
          <UserProfile 
            user={user!}
            onLogout={handleLogout}
            onBackToGame={() => setView('game')}
            onDeleteAccount={() => setView('deleteAccount')}
          />
        </div>
      </div>
    );
  }

  if (view === 'deleteAccount') {
    return (
      <div className="min-h-screen bg-gray-900 text-white flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-4xl mb-8">Delete Account</h1>
          <DeleteAccountPage 
            user={user!}
            onBackToProfile={() => setView('profile')}
            onAccountDeleted={handleLogout}
          />
        </div>
      </div>
    );
  }

  if (view === 'forgotPassword') {
    return (
      <div className="min-h-screen bg-gray-900 text-white flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-4xl mb-8">Forgot Password</h1>
          <ForgotPassword 
            onBackToLogin={() => setView('game')}
          />
        </div>
      </div>
    );
  }

  if (view === 'forgotUsername') {
    return (
      <div className="min-h-screen bg-gray-900 text-white flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-4xl mb-8">Forgot Username</h1>
          <ForgotUsername 
            onBackToLogin={() => setView('game')}
          />
        </div>
      </div>
    );
  }

  if (view === 'ranking') {
    return (
      <div className="min-h-screen bg-gray-900 text-white flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-4xl mb-8">User Ranking</h1>
          <Ranking />
          <button
            onClick={() => setView('game')}
            className="mt-8 px-4 py-2 bg-gray-600 rounded hover:bg-gray-700"
          >
            Back to Game
          </button>
        </div>
      </div>
    );
  }

  // Main game view
  return (
    <GameSettingsProvider>
      <div className="min-h-screen bg-gray-900 text-white flex items-center justify-center">
        <div className="text-center">
          <div className="flex justify-between items-center mb-8">
            <div className="text-left">
              <h1 className="text-4xl">Transcendence Pong</h1>
              <p className="text-gray-400 mt-2">Welcome, {user?.username}!</p>
            </div>
            <div className="flex gap-4">
              <button 
                onClick={() => setView('profile')}
                className="px-4 py-2 bg-blue-600 rounded hover:bg-blue-700"
              >
                Profile
              </button>
              <button 
                onClick={handleLogout}
                className="px-4 py-2 bg-red-600 rounded hover:bg-red-700"
              >
                Logout
              </button>
            </div>
          </div>
          {renderGameContent()}
        </div>
        
        {/* Game Settings Modal */}
        {showSettings && (
          <GameSettings 
            isOpen={showSettings}
            onClose={() => setShowSettings(false)}
          />
        )}
      </div>
    </GameSettingsProvider>
  );
}

export default App;

// srcs/services/frontend/src-svelte/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import LoginForm from './components/LoginForm.svelte';
  import RegisterForm from './components/RegisterForm.svelte';
  import UserProfile from './components/UserProfile.svelte';
  import PongGame from './components/PongGame.svelte';
  import AIPong from './components/AIPong.svelte';
  import MultiPlayerPong from './components/MultiPlayerPong.svelte';
  import Tournament from './components/Tournament.svelte';
  import Leaderboard from './components/Leaderboard.svelte';
  import ForgotUsername from './components/ForgotUsername.svelte';
  import ForgotPassword from './components/ForgotPassword.svelte';
  import { _, locale, isLoading as i18nLoading } from 'svelte-i18n';
  import { AuthService } from './shared/services/authService';
  import type { AuthResponse, User } from './shared/types/auth';

  // Game mode state
  let gameMode: 'menu' | 'single' | 'multiplayer' | 'ai' = 'menu';
  let roomId = '';
  let playerSide: 'left' | 'right' = 'left';

  // Authentication state
  let user: User | null = null;
  let isAuthenticated = false;
  let isLoading = true;
  let authMode: 'login' | 'register' = 'login';
  let view: 'game' | 'profile' | 'deleteAccount' | 'forgotPassword' | 'forgotUsername' | 'settings' | 'ranking' | 'tournament' = 'game';
  let showSettings = false;
  let selectedLanguage = 'en';

  // Check authentication status on component mount
  onMount(async () => {
    // Wait for i18n to load
    while ($i18nLoading) {
      await new Promise(resolve => setTimeout(resolve, 100));
    }
    await checkAuth();
  });

  const checkAuth = async () => {
    try {
      const storedAuth = AuthService.getStoredAuthData();
      if (storedAuth && AuthService.isAuthenticated()) {
        user = storedAuth.user;
        isAuthenticated = true;
      } else {
        // Clear invalid auth data
        AuthService.clearAuthData();
        user = null;
        isAuthenticated = false;
      }
    } catch (error) {
      console.error('Error checking authentication:', error);
      AuthService.clearAuthData();
      user = null;
      isAuthenticated = false;
    }
    isLoading = false;
  };

  // Handle successful authentication
  const handleAuthSuccess = (authData: AuthResponse) => {
    user = authData.user;
    isAuthenticated = true;
    view = 'game';
  };

  // Handle logout
  const handleLogout = () => {
    user = null;
    isAuthenticated = false;
    authMode = 'login';
    view = 'game';
    AuthService.clearAuthData();
  };

  // Game mode functions
  const startSinglePlayerGame = () => {
    gameMode = 'single';
  };

  const showMultiplayerSetup = () => {
    gameMode = 'multiplayer';
  };

  const startAIGame = () => {
    gameMode = 'ai';
  };

  const handleReturnToMenu = () => {
    gameMode = 'menu';
  };

  // Handle view changes
  const setView = (newView: typeof view) => {
    view = newView;
  };

  const setShowSettings = (show: boolean) => {
    showSettings = show;
  };
</script>

<main>
  <div class="min-h-screen bg-gray-900 text-white flex items-center justify-center">
    {#if isLoading || $i18nLoading}
      <div class="text-center">
        <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-white mx-auto mb-4"></div>
        <p>Loading...</p>
      </div>
    {:else if !isAuthenticated}
      <!-- Authentication Views -->
      <div class="text-center">
        <h1 class="text-4xl mb-8">{$_('label.title')}</h1>
        <p class="text-gray-400 mb-8">{$_('label.signintoplay')}</p>
        
        {#if authMode === 'login'}
          <LoginForm 
            onLoginSuccess={handleAuthSuccess}
            onSwitchToRegister={() => authMode = 'register'}
            onSwitchToForgotUsername={() => { view = 'forgotUsername'; }}
            onSwitchToForgotPassword={() => { view = 'forgotPassword'; }}
          />
        {:else}
          <RegisterForm 
            onRegisterSuccess={handleAuthSuccess}
            onSwitchToLogin={() => authMode = 'login'}
          />
        {/if}
        
        <!-- Forgot Password/Username Views (for unauthenticated users) -->
        {#if view === 'forgotUsername'}
          <ForgotUsername onBackToLogin={() => { view = 'game'; }} />
        {:else if view === 'forgotPassword'}
          <ForgotPassword onBackToLogin={() => { view = 'game'; }} />
        {/if}
      </div>
    {:else}
      <!-- Main Game View -->
      <div class="text-center">
        <div class="flex justify-between items-center mb-8">
          <div class="text-left">
            <h1 class="text-4xl">{$_('label.title')}</h1>
            <p class="text-gray-400 mt-2">{$_('label.welcomeuser', {user: user?.username || 'Guest'})}</p>
          </div>
          <div class="flex gap-4">
            <button 
              on:click={() => setView('profile')}
              class="px-4 py-2 bg-blue-600 rounded hover:bg-blue-700"
            >
              {$_('button.userprofile')}
            </button>
            <button 
              on:click={handleLogout}
              class="px-4 py-2 bg-red-600 rounded hover:bg-red-700"
            >
              {$_('button.logout')}
            </button>
          </div>
        </div>
        
        <!-- Game Content -->
        {#if view === 'game'}
          {#if gameMode === 'menu'}
            <!-- Main Menu -->
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-4xl mx-auto">
              <button 
                on:click={startSinglePlayerGame}
                class="p-6 bg-blue-600 rounded-lg hover:bg-blue-700 transition-colors"
              >
                <h3 class="text-xl font-bold mb-2">{$_('button.pvplocal')}</h3>
                <p class="text-gray-300">{$_('msg.movementkeys')}</p>
              </button>
              
              <button 
                on:click={showMultiplayerSetup}
                class="p-6 bg-green-600 rounded-lg hover:bg-green-700 transition-colors"
              >
                <h3 class="text-xl font-bold mb-2">{$_('button.mponline')}</h3>
                <p class="text-gray-300">Play with friends online</p>
              </button>
              
              <button 
                on:click={startAIGame}
                class="p-6 bg-purple-600 rounded-lg hover:bg-purple-700 transition-colors"
              >
                <h3 class="text-xl font-bold mb-2">{$_('button.pve')}</h3>
                <p class="text-gray-300">{$_('msg.aidifficulty')}</p>
              </button>
              
              <button 
                on:click={() => setView('tournament')}
                class="p-6 bg-yellow-600 rounded-lg hover:bg-yellow-700 transition-colors"
              >
                <h3 class="text-xl font-bold mb-2">{$_('button.tournament')}</h3>
                <p class="text-gray-300">Join or create tournaments</p>
              </button>
              
              <button 
                on:click={() => setView('ranking')}
                class="p-6 bg-indigo-600 rounded-lg hover:bg-indigo-700 transition-colors"
              >
                <h3 class="text-xl font-bold mb-2">{$_('button.ranking')}</h3>
                <p class="text-gray-300">{$_('msg.leaderboard')}</p>
              </button>
              
              <button 
                on:click={() => setShowSettings(true)}
                class="p-6 bg-gray-600 rounded-lg hover:bg-gray-700 transition-colors"
              >
                <h3 class="text-xl font-bold mb-2">{$_('button.settings')}</h3>
                <p class="text-gray-300">Game settings and preferences</p>
              </button>
            </div>
          {:else if gameMode === 'single'}
            <!-- Single Player Game -->
            <PongGame />
            <button 
              on:click={handleReturnToMenu}
              class="mt-4 px-4 py-2 bg-gray-600 rounded hover:bg-gray-700"
            >
              {$_('button.backtomenu')}
            </button>
          {:else if gameMode === 'multiplayer'}
            <!-- Multiplayer Setup -->
            <div class="mb-4">
              <input
                type="text"
                placeholder={$_('placeholder.roomid')}
                bind:value={roomId}
                class="px-4 py-2 text-black rounded mr-2"
              />
              <select
                bind:value={playerSide}
                class="px-4 py-2 text-black rounded mr-2"
              >
                <option value="left">{$_('option.leftplayer')}</option>
                <option value="right">{$_('option.rightplayer')}</option>
              </select>
            </div>
            <MultiPlayerPong {roomId} {playerSide} />
            <button 
              on:click={handleReturnToMenu}
              class="mt-4 px-4 py-2 bg-gray-600 rounded hover:bg-gray-700"
            >
              {$_('button.backtomenu')}
            </button>
          {:else if gameMode === 'ai'}
            <!-- AI Game -->
            <AIPong />
            <button 
              on:click={handleReturnToMenu}
              class="mt-4 px-4 py-2 bg-gray-600 rounded hover:bg-gray-700"
            >
              {$_('button.backtomenu')}
            </button>
          {/if}
        {:else if view === 'profile'}
          <!-- User Profile -->
          <UserProfile 
            {user}
            onBackToGame={() => setView('game')}
            onLogout={handleLogout}
            onDeleteAccount={() => setView('deleteAccount')}
          />
        {:else if view === 'tournament'}
          <!-- Tournament -->
          <Tournament 
            onBack={() => setView('game')}
            onStartMatch={(tournamentId, matchId, roomId) => {
              gameMode = 'multiplayer';
              roomId = roomId;
              playerSide = 'left';
              setView('game');
            }}
          />
        {:else if view === 'ranking'}
          <!-- Leaderboard -->
          <Leaderboard onBack={() => setView('game')} />
        {/if}
      </div>
    {/if}
    
    <!-- Settings Modal -->
    {#if showSettings}
      <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
        <div class="bg-white rounded-lg p-6 max-w-md w-full mx-4">
          <div class="flex justify-between items-center mb-4">
            <h2 class="text-2xl font-bold text-gray-900">Game Settings</h2>
            <button 
              on:click={() => setShowSettings(false)}
              class="text-gray-500 hover:text-gray-700 text-2xl"
            >
              ×
            </button>
          </div>
          
          <div class="space-y-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">
                Game Speed
              </label>
              <select class="w-full px-3 py-2 border border-gray-300 rounded-lg">
                <option value="slow">Slow</option>
                <option value="normal" selected>Normal</option>
                <option value="fast">Fast</option>
              </select>
            </div>
            
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">
                Sound Effects
              </label>
              <input type="checkbox" checked class="mr-2"> Enable sound effects
            </div>
            
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">
                Language
              </label>
              <select 
                bind:value={selectedLanguage}
                class="w-full px-3 py-2 border border-gray-300 rounded-lg"
              >
                <option value="en">English</option>
                <option value="ko">한국어</option>
                <option value="jp">日本語</option>
              </select>
            </div>
          </div>
          
          <div class="mt-6 flex justify-end space-x-3">
            <button 
              on:click={() => setShowSettings(false)}
              class="px-4 py-2 bg-gray-600 text-white rounded hover:bg-gray-700"
            >
              Cancel
            </button>
            <button 
              on:click={() => {
                locale.set(selectedLanguage);
                setShowSettings(false);
              }}
              class="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
            >
              Save
            </button>
          </div>
        </div>
      </div>
    {/if}
  </div>
</main>

<style>
  main {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  }
  
  .grid {
    display: grid;
  }
  
  .grid-cols-1 {
    grid-template-columns: repeat(1, minmax(0, 1fr));
  }
  
  @media (min-width: 768px) {
    .md\:grid-cols-2 {
      grid-template-columns: repeat(2, minmax(0, 1fr));
    }
  }
  
  @media (min-width: 1024px) {
    .lg\:grid-cols-3 {
      grid-template-columns: repeat(3, minmax(0, 1fr));
    }
  }
  
  .gap-6 {
    gap: 1.5rem;
  }
  
  .max-w-4xl {
    max-width: 56rem;
  }
  
  .mx-auto {
    margin-left: auto;
    margin-right: auto;
  }
  
  .p-6 {
    padding: 1.5rem;
  }
  
  .bg-blue-600 {
    background-color: rgb(37 99 235);
  }
  
  .bg-green-600 {
    background-color: rgb(22 163 74);
  }
  
  .bg-purple-600 {
    background-color: rgb(147 51 234);
  }
  
  .bg-yellow-600 {
    background-color: rgb(202 138 4);
  }
  
  .bg-indigo-600 {
    background-color: rgb(79 70 229);
  }
  
  .bg-gray-600 {
    background-color: rgb(75 85 99);
  }
  
  .hover\:bg-blue-700:hover {
    background-color: rgb(29 78 216);
  }
  
  .hover\:bg-green-700:hover {
    background-color: rgb(21 128 61);
  }
  
  .hover\:bg-purple-700:hover {
    background-color: rgb(126 34 206);
  }
  
  .hover\:bg-yellow-700:hover {
    background-color: rgb(161 98 7);
  }
  
  .hover\:bg-indigo-700:hover {
    background-color: rgb(67 56 202);
  }
  
  .hover\:bg-gray-700:hover {
    background-color: rgb(55 65 81);
  }
  
  .rounded-lg {
    border-radius: 0.5rem;
  }
  
  .transition-colors {
    transition-property: color, background-color, border-color, text-decoration-color, fill, stroke;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
    transition-duration: 150ms;
  }
  
  .text-xl {
    font-size: 1.25rem;
    line-height: 1.75rem;
  }
  
  .font-bold {
    font-weight: 700;
  }
  
  .mb-2 {
    margin-bottom: 0.5rem;
  }
  
  .text-gray-300 {
    color: rgb(209 213 219);
  }
  
  .animate-spin {
    animation: spin 1s linear infinite;
  }
  
  @keyframes spin {
    from {
      transform: rotate(0deg);
    }
    to {
      transform: rotate(360deg);
    }
  }
  
  .rounded-full {
    border-radius: 9999px;
  }
  
  .h-12 {
    height: 3rem;
  }
  
  .w-12 {
    width: 3rem;
  }
  
  .border-b-2 {
    border-bottom-width: 2px;
  }
  
  .border-white {
    border-color: rgb(255 255 255);
  }
  
  .mb-4 {
    margin-bottom: 1rem;
  }
  
  .text-black {
    color: rgb(0 0 0);
  }
  
  .mr-2 {
    margin-right: 0.5rem;
  }
  
  .mt-4 {
    margin-top: 1rem;
  }
  
  .px-4 {
    padding-left: 1rem;
    padding-right: 1rem;
  }
  
  .py-2 {
    padding-top: 0.5rem;
    padding-bottom: 0.5rem;
  }
  
  .rounded {
    border-radius: 0.25rem;
  }
  
  .hover\:bg-gray-700:hover {
    background-color: rgb(55 65 81);
  }
  
  .min-h-screen {
    min-height: 100vh;
  }
  
  .bg-gray-900 {
    background-color: rgb(17 24 39);
  }
  
  .text-white {
    color: rgb(255 255 255);
  }
  
  .flex {
    display: flex;
  }
  
  .items-center {
    align-items: center;
  }
  
  .justify-center {
    justify-content: center;
  }
  
  .text-center {
    text-align: center;
  }
  
  .text-4xl {
    font-size: 2.25rem;
    line-height: 2.5rem;
  }
  
  .mb-8 {
    margin-bottom: 2rem;
  }
  
  .text-gray-400 {
    color: rgb(156 163 175);
  }
  
  .mt-2 {
    margin-top: 0.5rem;
  }
  
  .justify-between {
    justify-content: space-between;
  }
  
  .gap-4 {
    gap: 1rem;
  }
  
  .bg-blue-600 {
    background-color: rgb(37 99 235);
  }
  
  .bg-red-600 {
    background-color: rgb(220 38 38);
  }
  
  .hover\:bg-blue-700:hover {
    background-color: rgb(29 78 216);
  }
  
  .hover\:bg-red-700:hover {
    background-color: rgb(185 28 28);
  }
  
  .text-left {
    text-align: left;
  }
</style>
