// srcs/services/frontend/src/components/AIPong.tsx
import React, { useState, useCallback } from 'react';
import { usePongEngine } from '../hooks/usePongEngine';
import { useHumanController } from '../hooks/useHumanController';
import { useAIController, AIDifficulty } from '../hooks/useAIController';
import { GameStatsService } from '../services/gameStatsService';

/**
 * The Player vs. AI Pong game component.
 * It assembles the core game engine with one human controller and one AI controller.
 * Features advanced AI with difficulty levels and adaptive behavior.
 */
export const AIPong: React.FC = () => {
  const [aiDifficulty, setAiDifficulty] = useState<AIDifficulty>('medium');
  const [showDebugInfo, setShowDebugInfo] = useState(false);
  const [aiDebugInfo, setAiDebugInfo] = useState({
    lastMove: 'none',
    ballDirection: 'left',
    aiPosition: 200,
    targetPosition: 200,
    isMoving: false,
    consecutiveMisses: 0,
    consecutiveHits: 0,
    difficulty: 'medium' as AIDifficulty,
    prediction: null as { x: number; y: number } | null,
    ballPosition: { x: 0, y: 0 },
    shouldMove: false,
    reactionDelay: 80,
    movementDirection: 0,
    distance: 0,
    forceMovement: false
  });

  // Handle game end
  const handleGameEnd = useCallback(async (winner: 'left' | 'right', leftScore: number, rightScore: number) => {
    try {
      // Save game result (current user is left player vs AI)
      await GameStatsService.saveGameResultSimple(winner, leftScore, rightScore, 'ai', 'left');
      console.log('AI game result saved successfully');
    } catch (error) {
      console.error('Failed to save AI game result:', error);
    }
  }, []);

  // 1. Initialize the core game engine. This is IDENTICAL to the other game mode.
  const { canvasRef, gameState, controls } = usePongEngine(800, 400, handleGameEnd);
  
  // 2. Initialize a controller for the LEFT paddle (the human player).
  useHumanController(controls.setPaddleMovement, 'left');
  
  // 3. Initialize a controller for the RIGHT paddle (the AI opponent).
  useAIController(
    controls.setPaddleMovement, 
    gameState, 
    aiDifficulty,
    (debugInfo) => {
      setAiDebugInfo({
        lastMove: debugInfo.lastMove !== 0 ? 'moving' : 'idle',
        ballDirection: gameState.ball?.dx > 0 ? 'right' : 'left',
        aiPosition: gameState.rightPaddle?.y || 200,
        targetPosition: debugInfo.prediction?.y || 200,
        isMoving: debugInfo.lastMove !== 0,
        consecutiveMisses: debugInfo.consecutiveMisses,
        consecutiveHits: debugInfo.consecutiveHits,
        difficulty: debugInfo.difficulty,
        prediction: debugInfo.prediction,
        ballPosition: debugInfo.ballPosition || { x: 0, y: 0 },
        shouldMove: debugInfo.shouldMove,
        reactionDelay: debugInfo.reactionDelay,
        movementDirection: debugInfo.movementDirection,
        distance: debugInfo.distance,
        forceMovement: debugInfo.forceMovement
      });
    }
  );

  // Handle difficulty change
  const handleDifficultyChange = (newDifficulty: AIDifficulty) => {
    console.log('Difficulty changing from', aiDifficulty, 'to', newDifficulty);
    
    // Pause game first if it's playing
    if (gameState.status === 'playing') {
      controls.pause();
    }
    
    // Reset game completely
    controls.reset();
    
    // Update difficulty after a short delay to ensure reset is complete
    setTimeout(() => {
      setAiDifficulty(newDifficulty);
      console.log('Difficulty updated to', newDifficulty);
    }, 100);
  };

  return (
    <div className="flex flex-col items-center space-y-4 p-4" data-testid="game-container">
      {/* Game Title */}
      <h2 className="text-2xl font-bold text-white mb-4">
        Player vs AI
      </h2>

      {/* Instructions */}
      <div className="text-white text-sm mb-4 text-center">
        <p>Use W (up) / S (down) to move your paddle.</p>
        <p>The AI adapts its difficulty based on your performance!</p>
        <p>AI Difficulty: {aiDifficulty}</p>
      </div>

      {/* Difficulty Selector */}
      <div className="flex space-x-2 mb-4">
        <span className="text-white mr-2">AI Difficulty:</span>
        <button
          onClick={() => handleDifficultyChange('easy')}
          className={`px-4 py-2 rounded ${
            aiDifficulty === 'easy'
              ? 'bg-blue-600 text-white'
              : 'bg-gray-600 text-gray-300 hover:bg-gray-500'
          }`}
        >
          Easy
        </button>
        <button
          onClick={() => handleDifficultyChange('medium')}
          className={`px-4 py-2 rounded ${
            aiDifficulty === 'medium'
              ? 'bg-blue-600 text-white'
              : 'bg-gray-600 text-gray-300 hover:bg-gray-500'
          }`}
        >
          Medium
        </button>
        <button
          onClick={() => handleDifficultyChange('hard')}
          className={`px-4 py-2 rounded ${
            aiDifficulty === 'hard'
              ? 'bg-blue-600 text-white'
              : 'bg-gray-600 text-gray-300 hover:bg-gray-500'
          }`}
        >
          Hard
        </button>
      </div>

      {/* Game Canvas */}
      <div className="relative">
        <canvas
          ref={canvasRef}
          width={800}
          height={400}
          className="border-2 border-white bg-black"
          aria-label="AI Pong game canvas"
        />
        
        {/* Game Controls Overlay */}
        <div className="absolute top-2 left-2 text-white text-sm">
          <div>Use W/S keys to move your paddle</div>
          <div>Press SPACE to start/pause</div>
        </div>

        {/* Score Display */}
        <div className="absolute top-2 right-2 text-white text-2xl font-bold" data-testid="score">
          Player: {gameState.leftScore} - AI: {gameState.rightScore}
        </div>
        
        {/* Game End Message */}
        {gameState.status === 'finished' && gameState.winner && (
          <div className="absolute inset-0 flex items-center justify-center bg-black bg-opacity-75">
            <div className="bg-green-600 text-white p-6 rounded-lg text-center">
              <h3 className="text-2xl font-bold mb-2">Game Over!</h3>
              <p className="text-xl mb-2">
                {gameState.winner === 'left' ? 'Player' : 'AI'} wins!
              </p>
              <p className="text-lg">Final Score: {gameState.leftScore} - {gameState.rightScore}</p>
            </div>
          </div>
        )}
      </div>

      {/* Game Controls */}
      <div className="flex space-x-4">
        <button
          onClick={controls.start}
          disabled={gameState.status === 'playing'}
          className="px-4 py-2 bg-green-600 text-white rounded hover:bg-green-700 disabled:bg-gray-600"
        >
          Start
        </button>
        <button
          onClick={controls.pause}
          disabled={gameState.status !== 'playing'}
          className="px-4 py-2 bg-yellow-600 text-white rounded hover:bg-yellow-700 disabled:bg-gray-600"
        >
          Pause
        </button>
        <button
          onClick={controls.reset}
          className="px-4 py-2 bg-red-600 text-white rounded hover:bg-red-700"
        >
          Reset
        </button>
        <button
          onClick={() => setShowDebugInfo(!showDebugInfo)}
          className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
        >
          {showDebugInfo ? 'Hide Debug' : 'Show Debug'}
        </button>
      </div>

      {/* AI Debug Information */}
      {showDebugInfo && (
        <div className="bg-gray-800 p-4 rounded-lg text-white text-sm max-w-md" data-testid="ai-debug-info">
          <h3 className="font-bold mb-2">AI Debug Info:</h3>
          <div className="space-y-1">
            <div>Difficulty: <span className="text-yellow-400">{aiDebugInfo.difficulty}</span></div>
            <div>Last Move: <span className="text-blue-400">{aiDebugInfo.lastMove}</span></div>
            <div>Ball Direction: <span className="text-green-400">{aiDebugInfo.ballDirection}</span></div>
            <div>Ball Position: <span className="text-cyan-400">
              ({Math.round(aiDebugInfo.ballPosition?.x || 0)}, {Math.round(aiDebugInfo.ballPosition?.y || 0)})
            </span></div>
            <div>AI Position: <span className="text-purple-400" data-testid="ai-position">{Math.round(aiDebugInfo.aiPosition)}</span></div>
            <div>Target Position: <span className="text-orange-400">{Math.round(aiDebugInfo.targetPosition)}</span></div>
            <div>Is Moving: <span className="text-red-400" data-testid="is-moving">{aiDebugInfo.isMoving ? 'Yes' : 'No'}</span></div>
            <div>Should Move: <span className="text-pink-400">{aiDebugInfo.shouldMove ? 'Yes' : 'No'}</span></div>
            <div>Reaction Delay: <span className="text-indigo-400">{aiDebugInfo.reactionDelay}ms</span></div>
            <div>Consecutive Misses: <span className="text-red-400">{aiDebugInfo.consecutiveMisses}</span></div>
            <div>Consecutive Hits: <span className="text-green-400">{aiDebugInfo.consecutiveHits}</span></div>
            {aiDebugInfo.prediction && (
              <div>Prediction: <span className="text-cyan-400">
                ({Math.round(aiDebugInfo.prediction.x)}, {Math.round(aiDebugInfo.prediction.y)})
              </span></div>
            )}
            <div>Movement Direction: <span className="text-blue-400" data-testid="movement-direction">{aiDebugInfo.movementDirection}</span></div>
            <div>Distance: <span className="text-purple-400">{aiDebugInfo.distance}</span></div>
            <div>Force Movement: <span className="text-red-400">{aiDebugInfo.forceMovement ? 'Yes' : 'No'}</span></div>
          </div>
        </div>
      )}

      {/* Game Status */}
      <div className="text-white text-lg" data-testid="game-status">
        Status: <span className="text-yellow-400">{gameState.status}</span>
      </div>
    </div>
  );
};

// srcs/services/frontend/src-svelte/components/AIPong.svelte
<!--
  The Player vs. AI Pong game component.
  It assembles the core game engine with one human controller and one AI controller.
  Features advanced AI with difficulty levels and adaptive behavior.
-->

<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { GameStatsService } from '../shared/services/gameStatsService';
  import { usePongEngine } from '../hooks/usePongEngine';
  import { useHumanController } from '../hooks/useHumanController';
  import { useAIController, type AIDifficulty } from '../hooks/useAIController';
  import { _ } from 'svelte-i18n';

  let canvasRef: HTMLCanvasElement;
  let gameState: any;
  let controls: any;
  
  let aiDifficulty: AIDifficulty = 'medium';
  let showDebugInfo = false;
  let aiDebugInfo = {
    lastMove: 'none',
    ballDirection: 'left',
    aiPosition: 200,
    targetPosition: 200,
    isMoving: false,
    consecutiveMisses: 0,
    consecutiveHits: 0,
    difficulty: 'medium' as AIDifficulty,
    prediction: null as { x: number; y: number } | null,
    ballPosition: { x: 0, y: 0 },
    shouldMove: false,
    reactionDelay: 80,
    movementDirection: 0,
    distance: 0,
    forceMovement: false
  };

  /**
   * Handle game end
   */
  const handleGameEnd = async (winner: 'left' | 'right', leftScore: number, rightScore: number) => {
    console.log(`AIPong: Game ended! Winner: ${winner}, Score: ${leftScore} - ${rightScore}`);
    try {
      // Save game result (current user is left player vs AI)
      await GameStatsService.saveGameResultSimple(winner, leftScore, rightScore, 'ai', 'left');
      console.log('AI game result saved successfully');
    } catch (error) {
      console.error('Failed to save AI game result:', error);
    }
  };

  let humanController: any;
  let aiController: any;

  onMount(() => {
    // Initialize the core game engine with canvas
    const engine = usePongEngine(canvasRef, 800, 400, handleGameEnd);
    gameState = engine.gameState;
    controls = engine.controls;
    
    // Initialize human controller for left paddle
    humanController = useHumanController(controls.setPaddleMovement, 'left');
    humanController.initialize();
    
    // Initialize AI controller for right paddle
    aiController = useAIController(controls.setPaddleMovement, 'right', aiDifficulty, (debugInfo) => {
      aiDebugInfo = debugInfo;
    });
  });

  onDestroy(() => {
    // Cleanup controllers
    if (humanController) {
      humanController.cleanup();
    }
    if (aiController) {
      aiController.cleanup();
    }
  });

  /**
   * Handle AI difficulty change
   */
  const handleDifficultyChange = (newDifficulty: AIDifficulty) => {
    aiDifficulty = newDifficulty;
    // Restart AI with new difficulty
    if (controls) {
      useAIController(controls.setPaddleMovement, 'right', newDifficulty, (debugInfo) => {
        aiDebugInfo = debugInfo;
      });
    }
  };
</script>

<div class="flex flex-col items-center" data-testid="ai-game-container">
  <h2 class="text-2xl mb-4">Player vs. AI</h2>
  
  <!-- Difficulty Selection -->
  <div class="mb-4 flex space-x-4">
    <label class="text-sm font-medium text-gray-700">{$_('label.difficulty')}:</label>
    <select
      bind:value={aiDifficulty}
      on:change={() => handleDifficultyChange(aiDifficulty)}
      class="px-3 py-1 border border-gray-300 rounded-md text-sm"
    >
      <option value="easy">{$_('difficulty.easy')}</option>
      <option value="medium">{$_('difficulty.medium')}</option>
      <option value="hard">{$_('difficulty.hard')}</option>
      <option value="expert">{$_('difficulty.expert')}</option>
    </select>
    
    <button
      on:click={() => showDebugInfo = !showDebugInfo}
      class="px-3 py-1 bg-gray-600 text-white rounded-md text-sm hover:bg-gray-700"
    >
      {showDebugInfo ? $_('button.hidedebug') : $_('button.showdebug')}
    </button>
  </div>
  
  <div class="mb-4 flex justify-center space-x-8">
    <div class="text-center">
      <div class="text-2xl font-bold text-blue-600">{gameState?.leftScore || 0}</div>
      <div class="text-sm text-gray-600">{$_('label.player')}</div>
    </div>
    <div class="text-center">
      <div class="text-2xl font-bold text-red-600">{gameState?.rightScore || 0}</div>
      <div class="text-sm text-gray-600">{$_('label.ai')}</div>
    </div>
  </div>

  <div class="relative">
    <canvas
      bind:this={canvasRef}
      width={800}
      height={400}
      class="border-2 border-gray-300 rounded-lg bg-black"
    ></canvas>
    
    {#if gameState?.status === 'paused'}
      <div class="absolute inset-0 flex items-center justify-center bg-black bg-opacity-50 rounded-lg">
        <div class="text-white text-xl font-bold">PAUSED</div>
      </div>
    {/if}
    
    {#if gameState?.status === 'finished'}
      <div class="absolute inset-0 flex items-center justify-center bg-black bg-opacity-50 rounded-lg">
        <div class="text-white text-xl font-bold">
          Game Over! Winner: {gameState?.winner === 'left' ? 'Player' : 'AI'}
        </div>
      </div>
    {/if}
  </div>

  <!-- Debug Info Panel -->
  {#if showDebugInfo}
    <div class="mt-4 p-4 bg-gray-100 rounded-lg text-sm">
      <h3 class="font-bold mb-2">{$_('label.aidebug')}</h3>
      <div class="grid grid-cols-2 gap-2">
        <div><strong>{$_('debug.lastmove')}:</strong> {aiDebugInfo.lastMove}</div>
        <div><strong>{$_('debug.ballpos')}:</strong> ({aiDebugInfo.ballPosition.x}, {aiDebugInfo.ballPosition.y})</div>
        <div><strong>{$_('debug.aipos')}:</strong> {aiDebugInfo.aiPosition}</div>
        <div><strong>{$_('debug.targetpos')}:</strong> {aiDebugInfo.targetPosition}</div>
        <div><strong>{$_('debug.ismoving')}:</strong> {aiDebugInfo.isMoving}</div>
        <div><strong>{$_('debug.distance')}:</strong> {aiDebugInfo.distance}</div>
        <div><strong>{$_('debug.hits')}:</strong> {aiDebugInfo.consecutiveHits}</div>
        <div><strong>{$_('debug.misses')}:</strong> {aiDebugInfo.consecutiveMisses}</div>
      </div>
    </div>
  {/if}

  <div class="mt-4 flex space-x-4">
    <button
      on:click={() => controls?.startGame()}
      disabled={gameState?.status === 'playing'}
      class="px-4 py-2 bg-green-600 text-white rounded hover:bg-green-700 disabled:bg-gray-400 disabled:cursor-not-allowed"
    >
      {$_('button.start')}
    </button>
    
    <button
      on:click={() => controls?.pauseGame()}
      disabled={gameState?.status !== 'playing'}
      class="px-4 py-2 bg-yellow-600 text-white rounded hover:bg-yellow-700 disabled:bg-gray-400 disabled:cursor-not-allowed"
    >
      {$_('button.pause')}
    </button>
    
    <button
      on:click={() => controls?.resetGame()}
      class="px-4 py-2 bg-red-600 text-white rounded hover:bg-red-700"
    >
      {$_('button.reset')}
    </button>
  </div>

  <div class="mt-4 text-sm text-gray-600 text-center">
    <p>{$_('instruction.player1')}: {$_('instruction.wskeys')}</p>
    <p>{$_('instruction.space')}: {$_('instruction.startpause')}</p>
  </div>
</div>
