// srcs/services/frontend/src/components/TournamentBracket.tsx
/**
 * Tournament Bracket Component
 * 
 * Interactive tournament bracket visualization with support for different tournament types
 */

import React, { useState, useEffect, useMemo } from 'react';
import { BracketNode, TournamentParticipant, TournamentMatch } from '../services/tournamentService';

interface Props {
  bracket: BracketNode[];
  matches: TournamentMatch[];
  tournamentType: 'single_elimination' | 'double_elimination' | 'round_robin';
  tournamentId?: number;
  onMatchClick?: (match: TournamentMatch) => void;
}

interface BracketPosition {
  x: number;
  y: number;
  width: number;
  height: number;
}

interface MatchBoxProps {
  node: BracketNode;
  position: BracketPosition;
  onClick?: () => void;
}

const MatchBox: React.FC<MatchBoxProps> = ({ node, position, onClick }) => {
  const player1 = node.player1;
  const player2 = node.player2;
  const winner = node.winner;

  const getPlayerDisplayName = (participant?: TournamentParticipant) => {
    if (!participant) return 'TBD';
    return participant.display_name || 'Unknown Player';
  };

  const getPlayerAvatar = (participant?: TournamentParticipant) => {
    if (!participant || !participant.avatar_url) {
      return (
        <div className="w-6 h-6 bg-gray-300 rounded-full flex items-center justify-center">
          <span className="text-xs font-medium text-gray-600">
            {participant && participant.display_name ? participant.display_name.charAt(0).toUpperCase() : '?'}
          </span>
        </div>
      );
    }
    return (
      <img 
        src={participant.avatar_url} 
        alt={participant.display_name}
        className="w-6 h-6 rounded-full object-cover"
      />
    );
  };

  // Get bracket type styling based on position
  const getBracketTypeStyling = () => {
    const bracketPos = node.position.x;
    switch (bracketPos) {
      case 1: // Main bracket
        return 'border-blue-500 bg-blue-50';
      case 2: // Losers bracket
        return 'border-red-500 bg-red-50';
      case 3: // Grand final
        return 'border-yellow-500 bg-yellow-50';
      default:
        return 'border-gray-300 bg-white';
    }
  };

  return (
    <div
      className={`absolute border-2 rounded-lg shadow-sm hover:shadow-md transition-shadow cursor-pointer ${getBracketTypeStyling()}`}
      style={{
        left: position.x,
        top: position.y,
        width: position.width,
        height: position.height,
      }}
      onClick={onClick}
    >
      <div className="p-3 h-full flex flex-col justify-between">
        {/* Player 1 */}
        <div className={`flex items-center gap-2 ${winner?.id === player1?.id ? 'font-bold text-green-600' : ''}`}>
          {getPlayerAvatar(player1)}
          <span className="text-sm truncate">{getPlayerDisplayName(player1)}</span>
        </div>

        {/* VS separator */}
        <div className="flex justify-center">
          <div className="w-4 h-px bg-gray-300"></div>
        </div>

        {/* Player 2 */}
        <div className={`flex items-center gap-2 ${winner?.id === player2?.id ? 'font-bold text-green-600' : ''}`}>
          {getPlayerAvatar(player2)}
          <span className="text-sm truncate">{getPlayerDisplayName(player2)}</span>
        </div>
      </div>

      {/* Match status indicator */}
      {node.match_id && (
        <div className="absolute -top-1 -right-1 w-3 h-3 rounded-full bg-blue-500"></div>
      )}
    </div>
  );
};

interface ConnectionLineProps {
  from: BracketPosition;
  to: BracketPosition;
  matchWidth: number;
  matchHeight: number;
}

const ConnectionLine: React.FC<ConnectionLineProps> = ({ from, to, matchWidth, matchHeight }) => {
  const startX = from.x + matchWidth;
  const startY = from.y + matchHeight / 2;
  const endX = to.x;
  const endY = to.y + matchHeight / 2;

  return (
    <svg
      className="absolute pointer-events-none"
      style={{
        left: Math.min(startX, endX),
        top: Math.min(startY, endY),
        width: Math.abs(endX - startX),
        height: Math.abs(endY - startY) + 2,
      }}
    >
      <path
        d={`M ${startX - Math.min(startX, endX)} ${startY - Math.min(startY, endY)} 
            L ${endX - Math.min(startX, endX)} ${endY - Math.min(startY, endY)}`}
        stroke="#6B7280"
        strokeWidth="2"
        fill="none"
        markerEnd="url(#arrowhead)"
      />
      <defs>
        <marker
          id="arrowhead"
          markerWidth="10"
          markerHeight="7"
          refX="9"
          refY="3.5"
          orient="auto"
        >
          <polygon
            points="0 0, 10 3.5, 0 7"
            fill="#6B7280"
          />
        </marker>
      </defs>
    </svg>
  );
};

export const TournamentBracket: React.FC<Props> = ({ 
  bracket, 
  matches, 
  tournamentType,
  tournamentId,
  onMatchClick 
}) => {
  const [containerSize, setContainerSize] = useState({ width: 0, height: 0 });
  const [zoom, setZoom] = useState(1);
  const [pan, setPan] = useState({ x: 0, y: 0 });

  // Round Robin table component
  const RoundRobinTable: React.FC = () => {
    const participants = bracket.map(node => node.player1).filter(Boolean);
    
    // Use actual matches from props instead of generating them
    const actualMatches = matches || [];
    
    return (
      <div className="w-full max-w-6xl mx-auto space-y-6">
        {/* Standings Table */}
        <div className="bg-white rounded-lg shadow-lg overflow-hidden">
          <div className="bg-gradient-to-r from-blue-600 to-purple-600 text-white px-6 py-4">
            <h3 className="text-xl font-bold">Round Robin Standings</h3>
            <p className="text-blue-100 text-sm">All participants play against each other</p>
          </div>
          
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Rank</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Player</th>
                  <th className="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">W</th>
                  <th className="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">L</th>
                  <th className="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Win%</th>
                  <th className="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">PF</th>
                  <th className="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">PA</th>
                  <th className="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Diff</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {participants.map((participant, index) => (
                  <tr key={participant?.id || index} className="hover:bg-gray-50">
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center">
                        <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                          index === 0 ? 'bg-yellow-100 text-yellow-800' :
                          index === 1 ? 'bg-gray-100 text-gray-800' :
                          index === 2 ? 'bg-orange-100 text-orange-800' :
                          'bg-gray-100 text-gray-600'
                        }`}>
                          {index + 1}
                        </span>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center">
                        <div className="flex-shrink-0 h-8 w-8">
                          {participant?.avatar_url ? (
                            <img className="h-8 w-8 rounded-full" src={participant.avatar_url} alt="" />
                          ) : (
                            <div className="h-8 w-8 rounded-full bg-gray-300 flex items-center justify-center">
                              <span className="text-sm font-medium text-gray-600">
                                {participant?.display_name?.charAt(0).toUpperCase() || '?'}
                              </span>
                            </div>
                          )}
                        </div>
                        <div className="ml-4">
                          <div className="text-sm font-medium text-gray-900">
                            {participant?.display_name || 'Unknown Player'}
                          </div>
                          <div className="text-sm text-gray-500">
                            {participant?.guest_alias || 'Guest'}
                          </div>
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-900">
                      {participant?.stats?.wins || 0}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-900">
                      {participant?.stats?.losses || 0}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-900">
                      {participant?.stats?.winRate ? (participant.stats.winRate * 100).toFixed(1) + '%' : '0.0%'}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-900">
                      {participant?.stats?.pointsFor || 0}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-900">
                      {participant?.stats?.pointsAgainst || 0}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-900">
                      {participant?.stats?.pointDifference || 0}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Matches Section */}
        <div className="bg-white rounded-lg shadow-lg overflow-hidden">
          <div className="bg-gradient-to-r from-green-600 to-teal-600 text-white px-6 py-4">
            <h3 className="text-xl font-bold">Round Robin Matches</h3>
            <p className="text-green-100 text-sm">Click to start a match</p>
          </div>
          
          <div className="p-6">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {actualMatches.map((match) => (
                <div key={match.id} className="border border-gray-200 rounded-lg p-4 hover:shadow-md transition-shadow">
                  <div className="flex items-center justify-between mb-3">
                    <span className="text-sm font-medium text-gray-600">Match {match.match_number}</span>
                    <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                      match.status === 'pending' ? 'bg-yellow-100 text-yellow-800' :
                      match.status === 'active' ? 'bg-blue-100 text-blue-800' :
                      'bg-green-100 text-green-800'
                    }`}>
                      {match.status}
                    </span>
                  </div>
                  
                  <div className="space-y-2">
                    <div className="flex items-center justify-between">
                      <span className="text-sm font-medium text-gray-900">
                        Player {match.player1_id}
                      </span>
                      <span className="text-sm text-gray-500">VS</span>
                      <span className="text-sm font-medium text-gray-900">
                        Player {match.player2_id}
                      </span>
                    </div>
                  </div>
                  
                  <div className="mt-4">
                    <button
                      onClick={() => {
                        if (tournamentId && match.id) {
                          window.location.href = `/game/tournament-${tournamentId}-match-${match.id}`;
                        }
                      }}
                      className="w-full bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-4 rounded-lg transition-colors"
                    >
                      Play Game
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    );
  };

  // Calculate single elimination layout
  const calculateSingleEliminationLayout = (
    nodesByRound: Map<number, BracketNode[]>,
    matchWidth: number,
    matchHeight: number,
    roundSpacing: number,
    matchSpacing: number
  ) => {
    const positions = new Map<number, BracketPosition>();
    const connections: Array<{ from: number; to: number }> = [];
    const rounds = Array.from(nodesByRound.keys()).sort((a, b) => a - b);
    let totalWidth = 0;
    let totalHeight = 0;

    rounds.forEach((round, roundIndex) => {
      const roundNodes = nodesByRound.get(round)!;
      const roundX = roundIndex * roundSpacing;
      
      const roundHeight = Math.max(roundNodes.length * matchSpacing, 200);
      totalHeight = Math.max(totalHeight, roundHeight);

      roundNodes.forEach((node, matchIndex) => {
        const y = (roundHeight - roundNodes.length * matchSpacing) / 2 + matchIndex * matchSpacing;
        
        positions.set(node.id, {
          x: roundX,
          y: y,
          width: matchWidth,
          height: matchHeight
        });

        // Calculate connections to next round
        if (roundIndex < rounds.length - 1) {
          const nextRound = rounds[roundIndex + 1];
          const nextRoundNodes = nodesByRound.get(nextRound)!;
          
          const nextMatchIndex = Math.floor(matchIndex / 2);
          if (nextMatchIndex < nextRoundNodes.length) {
            const nextNode = nextRoundNodes[nextMatchIndex];
            connections.push({ from: node.id, to: nextNode.id });
          }
        }
      });

      totalWidth = Math.max(totalWidth, roundX + matchWidth);
    });

    return { positions, connections, totalWidth, totalHeight };
  };

  // Calculate double elimination layout
  const calculateDoubleEliminationLayout = (
    mainBracketNodes: Map<number, BracketNode[]>,
    losersBracketNodes: Map<number, BracketNode[]>,
    grandFinalNodes: Map<number, BracketNode[]>,
    matchWidth: number,
    matchHeight: number,
    roundSpacing: number,
    matchSpacing: number,
    bracketSpacing: number
  ) => {
    const positions = new Map<number, BracketPosition>();
    
    let totalWidth = 0;
    let totalHeight = 0;

    // Calculate main bracket (winners bracket)
    const mainRounds = Array.from(mainBracketNodes.keys()).sort((a, b) => a - b);
    let mainBracketWidth = 0;
    let mainBracketHeight = 0;

    mainRounds.forEach((round, roundIndex) => {
      const roundNodes = mainBracketNodes.get(round)!;
      const roundX = roundIndex * roundSpacing;
      
      const roundHeight = Math.max(roundNodes.length * matchSpacing, 200);
      mainBracketHeight = Math.max(mainBracketHeight, roundHeight);

      roundNodes.forEach((node, matchIndex) => {
        const y = (roundHeight - roundNodes.length * matchSpacing) / 2 + matchIndex * matchSpacing;
        
        positions.set(node.id, {
          x: roundX,
          y: y,
          width: matchWidth,
          height: matchHeight
        });
      });

      mainBracketWidth = Math.max(mainBracketWidth, roundX + matchWidth);
    });

    // Calculate losers bracket
    const losersRounds = Array.from(losersBracketNodes.keys()).sort((a, b) => a - b);
    let losersBracketWidth = 0;
    let losersBracketHeight = 0;

    losersRounds.forEach((round, roundIndex) => {
      const roundNodes = losersBracketNodes.get(round)!;
      const roundX = mainBracketWidth + bracketSpacing + roundIndex * roundSpacing;
      
      const roundHeight = Math.max(roundNodes.length * matchSpacing, 200);
      losersBracketHeight = Math.max(losersBracketHeight, roundHeight);

      roundNodes.forEach((node, matchIndex) => {
        const y = (roundHeight - roundNodes.length * matchSpacing) / 2 + matchIndex * matchSpacing;
        
        positions.set(node.id, {
          x: roundX,
          y: y,
          width: matchWidth,
          height: matchHeight
        });
      });

      losersBracketWidth = Math.max(losersBracketWidth, roundX + matchWidth);
    });

    // Calculate grand final
    const grandFinalRounds = Array.from(grandFinalNodes.keys()).sort((a, b) => a - b);
    let grandFinalWidth = 0;
    let grandFinalHeight = 0;

    grandFinalRounds.forEach((round, roundIndex) => {
      const roundNodes = grandFinalNodes.get(round)!;
      const roundX = losersBracketWidth + bracketSpacing + roundIndex * roundSpacing;
      
      const roundHeight = Math.max(roundNodes.length * matchSpacing, 200);
      grandFinalHeight = Math.max(grandFinalHeight, roundHeight);

      roundNodes.forEach((node, matchIndex) => {
        const y = (roundHeight - roundNodes.length * matchSpacing) / 2 + matchIndex * matchSpacing;
        
        positions.set(node.id, {
          x: roundX,
          y: y,
          width: matchWidth,
          height: matchHeight
        });
      });

      grandFinalWidth = Math.max(grandFinalWidth, roundX + matchWidth);
    });

    totalWidth = Math.max(mainBracketWidth, losersBracketWidth, grandFinalWidth);
    totalHeight = Math.max(mainBracketHeight, losersBracketHeight, grandFinalHeight);

    return { positions, connections: [], totalWidth, totalHeight };
  };

  // Calculate bracket layout
  const bracketLayout = useMemo(() => {
    if (bracket.length === 0) return { positions: new Map<number, BracketPosition>(), connections: [], totalWidth: 0, totalHeight: 0 };

    const matchWidth = 200;
    const matchHeight = 80;
    const roundSpacing = 250;
    const matchSpacing = 100;
    const bracketSpacing = 400; // Space between main and losers bracket

    // Group nodes by round and bracket position
    const nodesByRound = new Map<number, BracketNode[]>();
    const mainBracketNodes = new Map<number, BracketNode[]>();
    const losersBracketNodes = new Map<number, BracketNode[]>();
    const grandFinalNodes = new Map<number, BracketNode[]>();

    bracket.forEach(node => {
      if (!nodesByRound.has(node.round)) {
        nodesByRound.set(node.round, []);
      }
      nodesByRound.get(node.round)!.push(node);

      // Group by bracket position for double elimination
      if (tournamentType === 'double_elimination') {
        const bracketPos = node.position.x; // 1 = main, 2 = losers, 3 = grand final
        if (bracketPos === 1) {
          if (!mainBracketNodes.has(node.round)) {
            mainBracketNodes.set(node.round, []);
          }
          mainBracketNodes.get(node.round)!.push(node);
        } else if (bracketPos === 2) {
          if (!losersBracketNodes.has(node.round)) {
            losersBracketNodes.set(node.round, []);
          }
          losersBracketNodes.get(node.round)!.push(node);
        } else if (bracketPos === 3) {
          if (!grandFinalNodes.has(node.round)) {
            grandFinalNodes.set(node.round, []);
          }
          grandFinalNodes.get(node.round)!.push(node);
        }
      }
    });

    if (tournamentType === 'double_elimination') {
      return calculateDoubleEliminationLayout(
        mainBracketNodes,
        losersBracketNodes,
        grandFinalNodes,
        matchWidth,
        matchHeight,
        roundSpacing,
        matchSpacing,
        bracketSpacing
      );
    } else {
      // Single elimination or round robin layout
      return calculateSingleEliminationLayout(
        nodesByRound,
        matchWidth,
        matchHeight,
        roundSpacing,
        matchSpacing
      );
    }
  }, [bracket, tournamentType]);

  // Handle container resize
  useEffect(() => {
    const handleResize = () => {
      const container = document.getElementById('bracket-container');
      if (container) {
        setContainerSize({
          width: container.clientWidth,
          height: container.clientHeight
        });
      }
    };

    handleResize();
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  // Auto-fit zoom
  useEffect(() => {
    if (containerSize.width > 0 && containerSize.height > 0 && bracketLayout.totalWidth > 0) {
      const scaleX = (containerSize.width - 100) / bracketLayout.totalWidth;
      const scaleY = (containerSize.height - 100) / bracketLayout.totalHeight;
      const autoZoom = Math.min(scaleX, scaleY, 1);
      setZoom(autoZoom);
    }
  }, [containerSize, bracketLayout]);

  // Handle zoom controls
  const handleZoomIn = () => setZoom(prev => Math.min(prev * 1.2, 2));
  const handleZoomOut = () => setZoom(prev => Math.max(prev / 1.2, 0.1));
  const handleResetZoom = () => {
    if (containerSize.width > 0 && bracketLayout.totalWidth > 0) {
      const scaleX = (containerSize.width - 100) / bracketLayout.totalWidth;
      const scaleY = (containerSize.height - 100) / bracketLayout.totalHeight;
      const autoZoom = Math.min(scaleX, scaleY, 1);
      setZoom(autoZoom);
    }
    setPan({ x: 0, y: 0 });
  };

  // Handle panning
  const [isDragging, setIsDragging] = useState(false);
  const [dragStart, setDragStart] = useState({ x: 0, y: 0 });

  const handleMouseDown = (e: React.MouseEvent) => {
    setIsDragging(true);
    setDragStart({ x: e.clientX - pan.x, y: e.clientY - pan.y });
  };

  const handleMouseMove = (e: React.MouseEvent) => {
    if (isDragging) {
      setPan({
        x: e.clientX - dragStart.x,
        y: e.clientY - dragStart.y
      });
    }
  };

  const handleMouseUp = () => {
    setIsDragging(false);
  };

  if (bracket.length === 0) {
    return (
      <div className="flex items-center justify-center h-64 bg-gray-50 rounded-lg">
        <div className="text-center text-gray-500">
          <p className="text-lg">No bracket data available</p>
          <p className="text-sm mt-2">Tournament bracket will appear here once matches are generated</p>
        </div>
      </div>
    );
  }

  // Show Round Robin table for round robin tournaments
  if (tournamentType === 'round_robin') {
    return <RoundRobinTable />;
  }

  return (
    <div className="space-y-4">
      {/* Controls */}
      <div className="flex justify-between items-center">
        <div className="flex items-center gap-2">
          <button
            onClick={handleZoomOut}
            className="px-3 py-1 bg-gray-200 hover:bg-gray-300 rounded text-sm"
          >
            -
          </button>
          <span className="text-sm text-gray-600 min-w-[60px] text-center">
            {Math.round(zoom * 100)}%
          </span>
          <button
            onClick={handleZoomIn}
            className="px-3 py-1 bg-gray-200 hover:bg-gray-300 rounded text-sm"
          >
            +
          </button>
          <button
            onClick={handleResetZoom}
            className="px-3 py-1 bg-blue-200 hover:bg-blue-300 rounded text-sm ml-2"
          >
            Reset
          </button>
        </div>
        
        <div className="text-sm text-gray-600">
          {tournamentType === 'single_elimination' && 'Single Elimination'}
          {tournamentType === 'double_elimination' && (
            <div className="flex items-center gap-4">
              <span>Double Elimination</span>
              <div className="flex items-center gap-2">
                <div className="w-3 h-3 rounded bg-blue-500"></div>
                <span className="text-xs">Main Bracket</span>
              </div>
              <div className="flex items-center gap-2">
                <div className="w-3 h-3 rounded bg-red-500"></div>
                <span className="text-xs">Losers Bracket</span>
              </div>
              <div className="flex items-center gap-2">
                <div className="w-3 h-3 rounded bg-yellow-500"></div>
                <span className="text-xs">Grand Final</span>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Bracket container */}
      <div
        id="bracket-container"
        className="relative w-full h-96 bg-gray-50 rounded-lg border overflow-hidden"
        onMouseDown={handleMouseDown}
        onMouseMove={handleMouseMove}
        onMouseUp={handleMouseUp}
        onMouseLeave={handleMouseUp}
        style={{ cursor: isDragging ? 'grabbing' : 'grab' }}
      >
        <div
          className="absolute"
          style={{
            transform: `translate(${pan.x}px, ${pan.y}px) scale(${zoom})`,
            transformOrigin: '0 0',
            width: bracketLayout.totalWidth,
            height: bracketLayout.totalHeight,
          }}
        >
          {/* Connection lines */}
          {bracketLayout.connections.map((connection, index) => {
            const fromPos = bracketLayout.positions.get(connection.from);
            const toPos = bracketLayout.positions.get(connection.to);
            
            if (!fromPos || !toPos) return null;
            
            return (
              <ConnectionLine
                key={index}
                from={fromPos}
                to={toPos}
                matchWidth={200}
                matchHeight={80}
              />
            );
          })}

          {/* Bracket labels for double elimination */}
          {tournamentType === 'double_elimination' && (
            <>
              {/* Main bracket label */}
              <div
                className="absolute bg-blue-500 text-white px-3 py-1 rounded-lg text-sm font-medium"
                style={{
                  left: 10,
                  top: 10,
                }}
              >
                Main Bracket (Winners)
              </div>
              
              {/* Losers bracket label */}
              <div
                className="absolute bg-red-500 text-white px-3 py-1 rounded-lg text-sm font-medium"
                style={{
                  left: 10 + 400, // Position after main bracket
                  top: 10,
                }}
              >
                Losers Bracket
              </div>
              
              {/* Grand final label */}
              <div
                className="absolute bg-yellow-500 text-white px-3 py-1 rounded-lg text-sm font-medium"
                style={{
                  left: 10 + 400 + 400, // Position after losers bracket
                  top: 10,
                }}
              >
                Grand Final
              </div>
            </>
          )}

          {/* Match boxes */}
          {bracket.map((node) => {
            const position = bracketLayout.positions.get(node.id);
            if (!position) return null;

            return (
              <MatchBox
                key={node.id}
                node={node}
                position={position}
                onClick={() => {
                  if (node.match_id && onMatchClick) {
                    const match = matches.find(m => m.id === node.match_id);
                    if (match) onMatchClick(match);
                  }
                }}
              />
            );
          })}
        </div>

        {/* Empty state overlay */}
        {bracketLayout.totalWidth === 0 && (
          <div className="absolute inset-0 flex items-center justify-center">
            <div className="text-center text-gray-500">
              <p className="text-lg">Generating bracket...</p>
              <p className="text-sm mt-2">Please wait while the tournament bracket is being created</p>
            </div>
          </div>
        )}
      </div>

      {/* Legend */}
      <div className="flex items-center gap-6 text-sm text-gray-600">
        <div className="flex items-center gap-2">
          <div className="w-3 h-3 rounded-full bg-blue-500"></div>
          <span>Active Match</span>
        </div>
        <div className="flex items-center gap-2">
          <div className="w-3 h-3 rounded-full bg-green-500"></div>
          <span>Winner</span>
        </div>
        <div className="flex items-center gap-2">
          <div className="w-3 h-3 rounded-full bg-gray-400"></div>
          <span>Pending</span>
        </div>
      </div>
    </div>
  );
};

// srcs/services/frontend/src-svelte/components/TournamentBracket.svelte
<!--
  TournamentBracket.svelte - Tournament Bracket Visualization
  Interactive tournament bracket with support for different tournament types
-->

<script lang="ts">
  import { onMount, createEventDispatcher } from 'svelte';
  import type { BracketNode, TournamentParticipant, TournamentMatch } from '../shared/services/tournamentService';

  // Props
  export let bracket: BracketNode[];
  export let matches: TournamentMatch[];
  export let tournamentType: 'single_elimination' | 'double_elimination' | 'round_robin';
  export let tournamentId: number | undefined = undefined;
  export let onMatchClick: ((match: TournamentMatch) => void) | undefined = undefined;

  const dispatch = createEventDispatcher();

  // State
  let containerSize = { width: 0, height: 0 };
  let zoom = 1;
  let pan = { x: 0, y: 0 };
  let container: HTMLDivElement;

  // Bracket positioning
  interface BracketPosition {
    x: number;
    y: number;
    width: number;
    height: number;
  }

  const matchWidth = 200;
  const matchHeight = 80;
  const matchSpacing = 50;
  const roundSpacing = 300;

  onMount(() => {
    updateContainerSize();
    window.addEventListener('resize', updateContainerSize);
    return () => window.removeEventListener('resize', updateContainerSize);
  });

  function updateContainerSize() {
    if (container) {
      containerSize = {
        width: container.clientWidth,
        height: container.clientHeight
      };
    }
  }

  function getPlayerDisplayName(participant?: TournamentParticipant): string {
    if (!participant) return 'TBD';
    return participant.display_name || 'Unknown Player';
  }

  function getPlayerAvatar(participant?: TournamentParticipant): string {
    if (!participant || !participant.avatar_url) {
      return '';
    }
    return participant.avatar_url;
  }

  function getBracketTypeStyling(node: BracketNode): string {
    const bracketPos = node.position.x;
    switch (bracketPos) {
      case 1: // Main bracket
        return 'border-blue-500 bg-blue-50';
      case 2: // Losers bracket
        return 'border-red-500 bg-red-50';
      case 3: // Grand final
        return 'border-yellow-500 bg-yellow-50';
      default:
        return 'border-gray-300 bg-white';
    }
  }

  function calculateBracketPositions(): BracketPosition[] {
    const positions: BracketPosition[] = [];
    
    if (tournamentType === 'round_robin') {
      return positions; // Round robin doesn't use bracket positions
    }

    // Calculate positions for elimination brackets
    const rounds = Math.ceil(Math.log2(bracket.length));
    
    bracket.forEach((node, index) => {
      const round = Math.floor(index / Math.pow(2, Math.floor(Math.log2(index + 1))));
      const positionInRound = index % Math.pow(2, round);
      
      const x = round * roundSpacing + 50;
      const y = positionInRound * (matchHeight + matchSpacing) + 50;
      
      positions.push({
        x,
        y,
        width: matchWidth,
        height: matchHeight
      });
    });

    return positions;
  }

  function handleMatchClick(node: BracketNode) {
    if (node.match_id && onMatchClick) {
      const match = matches.find(m => m.id === node.match_id);
      if (match) {
        console.log('Bracket match clicked:', {
          node: node,
          match: match,
          tournamentId: tournamentId
        });
        onMatchClick(match);
      }
    } else {
      console.warn('Match click handler not available:', {
        match_id: node.match_id,
        onMatchClick: !!onMatchClick
      });
    }
  }

  function handlePlayMatch(match: TournamentMatch) {
    if (onMatchClick) {
      console.log('Play match clicked:', {
        match: match,
        tournamentId: tournamentId
      });
      onMatchClick(match);
    } else {
      console.warn('Match click handler not available for match:', match.id);
    }
  }

  function handleZoomIn() {
    setZoom(Math.min(zoom * 1.2, 3));
  }

  function handleZoomOut() {
    setZoom(Math.max(zoom / 1.2, 0.3));
  }

  function handleReset() {
    setZoom(1);
    setPan({ x: 0, y: 0 });
  }

  function setZoom(newZoom: number) {
    zoom = newZoom;
  }

  function setPan(newPan: { x: number; y: number }) {
    pan = newPan;
  }

  // Round Robin specific functions
  function getRoundRobinStandings() {
    const participants = bracket.map(node => node.player1).filter(Boolean);
    const standings = participants.map(participant => ({
      participant,
      wins: 0,
      losses: 0,
      pointsFor: 0,
      pointsAgainst: 0
    }));

    // Calculate standings from matches
    matches.forEach(match => {
      if (match.winner_id && match.player1_id && match.player2_id) {
        const winnerStanding = standings.find(s => s.participant.id === match.winner_id);
        const loserStanding = standings.find(s => 
          s.participant.id === (match.winner_id === match.player1_id ? match.player2_id : match.player1_id)
        );

        if (winnerStanding) {
          winnerStanding.wins++;
          winnerStanding.pointsFor += match.player1_score || 0;
          winnerStanding.pointsAgainst += match.player2_score || 0;
        }
        if (loserStanding) {
          loserStanding.losses++;
          loserStanding.pointsFor += match.player2_score || 0;
          loserStanding.pointsAgainst += match.player1_score || 0;
        }
      }
    });

    // Sort by wins, then by win percentage
    return standings.sort((a, b) => {
      const aWinPct = a.wins / (a.wins + a.losses) || 0;
      const bWinPct = b.wins / (b.wins + b.losses) || 0;
      if (a.wins !== b.wins) return b.wins - a.wins;
      return bWinPct - aWinPct;
    });
  }

  function getWinPercentage(wins: number, losses: number): number {
    const total = wins + losses;
    return total > 0 ? Math.round((wins / total) * 100) : 0;
  }

  const positions = calculateBracketPositions();
  const standings = getRoundRobinStandings();
</script>

<div class="tournament-bracket-container">
  {#if tournamentType === 'round_robin'}
    <!-- Round Robin Table -->
    <div class="w-full max-w-6xl mx-auto space-y-6">
      <!-- Standings Table -->
      <div class="bg-white rounded-lg shadow-lg overflow-hidden">
        <div class="bg-gradient-to-r from-blue-600 to-purple-600 text-white px-6 py-4">
          <h3 class="text-xl font-bold">Round Robin Standings</h3>
          <p class="text-blue-100 text-sm">All participants play against each other</p>
        </div>
        
        <div class="overflow-x-auto">
          <table class="w-full">
            <thead class="bg-gray-50">
              <tr>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Rank</th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Player</th>
                <th class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">W</th>
                <th class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">L</th>
                <th class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Win%</th>
                <th class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">PF</th>
                <th class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">PA</th>
                <th class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Diff</th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              {#each standings as standing, index}
                <tr class="hover:bg-gray-50">
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                    {index + 1}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap">
                    <div class="flex items-center">
                      <div class="w-8 h-8 bg-blue-100 rounded-full flex items-center justify-center mr-3">
                        <span class="text-blue-600 font-medium text-sm">
                          {standing.participant.display_name?.charAt(0).toUpperCase() || '?'}
                        </span>
                      </div>
                      <div class="text-sm font-medium text-gray-900">
                        {standing.participant.display_name || 'Unknown Player'}
                      </div>
                    </div>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-center text-gray-900">
                    {standing.wins}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-center text-gray-900">
                    {standing.losses}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-center text-gray-900">
                    {getWinPercentage(standing.wins, standing.losses)}%
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-center text-gray-900">
                    {standing.pointsFor}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-center text-gray-900">
                    {standing.pointsAgainst}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-center text-gray-900">
                    {standing.pointsFor - standing.pointsAgainst}
                  </td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>
      </div>

      <!-- Matches Grid -->
      <div class="bg-white rounded-lg shadow-lg overflow-hidden">
        <div class="bg-gradient-to-r from-green-600 to-blue-600 text-white px-6 py-4">
          <h3 class="text-xl font-bold">Matches</h3>
          <p class="text-green-100 text-sm">All matches in this tournament</p>
        </div>
        
        <div class="p-6">
          <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {#each matches as match (match.id)}
              <div class="border border-gray-200 rounded-lg p-4 hover:shadow-md transition-shadow">
                <div class="flex justify-between items-center mb-2">
                  <span class="text-sm font-medium text-gray-600">Match #{match.id}</span>
                  <span class="px-2 py-1 rounded text-xs font-medium {match.status === 'completed' ? 'bg-green-100 text-green-800' : match.status === 'active' ? 'bg-blue-100 text-blue-800' : 'bg-yellow-100 text-yellow-800'}">
                    {match.status === 'completed' ? 'Completed' : match.status === 'active' ? 'Active' : 'Pending'}
                  </span>
                </div>
                
                <div class="space-y-2">
                  <div class="flex items-center justify-between">
                    <span class="text-sm {match.winner_id === match.player1_id ? 'font-bold text-green-600' : ''}">
                      {match.player1?.display_name || 'TBD'}
                    </span>
                    <span class="text-sm font-medium">{match.player1_score || 0}</span>
                  </div>
                  
                  <div class="flex items-center justify-between">
                    <span class="text-sm {match.winner_id === match.player2_id ? 'font-bold text-green-600' : ''}">
                      {match.player2?.display_name || 'TBD'}
                    </span>
                    <span class="text-sm font-medium">{match.player2_score || 0}</span>
                  </div>
                </div>

                <!-- Play/Join Button -->
                {#if match.status === 'pending' && match.player1_id && match.player2_id}
                  <div class="mt-3">
                    <button 
                      on:click={() => handlePlayMatch(match)}
                      class="w-full px-3 py-2 bg-green-600 text-white rounded hover:bg-green-700 transition-colors text-sm"
                    >
                      Play Match
                    </button>
                  </div>
                {:else if match.status === 'active'}
                  <div class="mt-3">
                    <button 
                      on:click={() => handlePlayMatch(match)}
                      class="w-full px-3 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 transition-colors text-sm"
                    >
                      Join Match
                    </button>
                  </div>
                {:else if match.status === 'completed'}
                  <div class="mt-3">
                    <div class="w-full px-3 py-2 bg-gray-100 text-gray-600 rounded text-sm text-center">
                      Match Completed
                    </div>
                  </div>
                {/if}
              </div>
            {/each}
          </div>
        </div>
      </div>
    </div>
  {:else}
    <!-- Elimination Bracket -->
    <div class="bracket-controls mb-4">
      <div class="flex space-x-2">
        <button 
          on:click={handleZoomIn}
          class="px-3 py-1 bg-blue-600 text-white rounded hover:bg-blue-700"
        >
          Zoom In
        </button>
        <button 
          on:click={handleZoomOut}
          class="px-3 py-1 bg-blue-600 text-white rounded hover:bg-blue-700"
        >
          Zoom Out
        </button>
        <button 
          on:click={handleReset}
          class="px-3 py-1 bg-gray-600 text-white rounded hover:bg-gray-700"
        >
          Reset
        </button>
      </div>
    </div>

    <div 
      bind:this={container}
      class="bracket-container relative overflow-auto border border-gray-300 rounded-lg"
      style="height: 600px;"
    >
      <div 
        class="bracket-content relative"
        style="transform: scale({zoom}) translate({pan.x}px, {pan.y}px); transform-origin: 0 0; min-width: 1200px; min-height: 400px;"
      >
        {#each bracket as node, index (node.id)}
          {@const position = positions[index]}
          {#if position}
            <!-- Match Box -->
            <div
              class="absolute border-2 rounded-lg shadow-sm hover:shadow-md transition-shadow cursor-pointer {getBracketTypeStyling(node)}"
              style="left: {position.x}px; top: {position.y}px; width: {position.width}px; height: {position.height}px;"
              on:click={() => handleMatchClick(node)}
            >
              <div class="p-3 h-full flex flex-col justify-between">
                <!-- Player 1 -->
                <div class="flex items-center gap-2 {node.winner?.id === node.player1?.id ? 'font-bold text-green-600' : ''}">
                  {#if getPlayerAvatar(node.player1)}
                    <img 
                      src={getPlayerAvatar(node.player1)} 
                      alt={getPlayerDisplayName(node.player1)}
                      class="w-6 h-6 rounded-full object-cover"
                    />
                  {:else}
                    <div class="w-6 h-6 bg-gray-300 rounded-full flex items-center justify-center">
                      <span class="text-xs font-medium text-gray-600">
                        {node.player1?.display_name?.charAt(0).toUpperCase() || '?'}
                      </span>
                    </div>
                  {/if}
                  <div class="flex flex-col">
                    <span class="text-sm truncate">{getPlayerDisplayName(node.player1)}</span>
                    <span class="text-xs text-blue-600 font-medium">Left</span>
                  </div>
                </div>

                <!-- VS separator -->
                <div class="flex justify-center">
                  <div class="w-4 h-px bg-gray-300"></div>
                </div>

                <!-- Player 2 -->
                <div class="flex items-center gap-2 {node.winner?.id === node.player2?.id ? 'font-bold text-green-600' : ''}">
                  {#if getPlayerAvatar(node.player2)}
                    <img 
                      src={getPlayerAvatar(node.player2)} 
                      alt={getPlayerDisplayName(node.player2)}
                      class="w-6 h-6 rounded-full object-cover"
                    />
                  {:else}
                    <div class="w-6 h-6 bg-gray-300 rounded-full flex items-center justify-center">
                      <span class="text-xs font-medium text-gray-600">
                        {node.player2?.display_name?.charAt(0).toUpperCase() || '?'}
                      </span>
                    </div>
                  {/if}
                  <div class="flex flex-col">
                    <span class="text-sm truncate">{getPlayerDisplayName(node.player2)}</span>
                    <span class="text-xs text-red-600 font-medium">Right</span>
                  </div>
                </div>
              </div>

              <!-- Match status indicator and Play button -->
              {#if node.match_id}
                <div class="absolute -top-1 -right-1 w-3 h-3 rounded-full bg-blue-500"></div>
                <!-- Play Match Button -->
                {#if node.player1 && node.player2}
                  <div class="absolute bottom-1 left-1 right-1">
                    <button 
                      on:click={() => handleMatchClick(node)}
                      class="w-full px-2 py-1 bg-green-600 text-white text-xs rounded hover:bg-green-700 transition-colors"
                    >
                      Play
                    </button>
                  </div>
                {/if}
              {/if}
            </div>
          {/if}
        {/each}

        <!-- Connection Lines -->
        {#each bracket as node, index}
          {@const position = positions[index]}
          {#if position && node.parent}
            {@const parentIndex = bracket.findIndex(n => n.id === node.parent?.id)}
            {@const parentPosition = positions[parentIndex]}
            {#if parentPosition}
              <svg
                class="absolute pointer-events-none"
                style="left: {Math.min(position.x + matchWidth, parentPosition.x)}px; top: {Math.min(position.y + matchHeight / 2, parentPosition.y + matchHeight / 2)}px; width: {Math.abs(parentPosition.x - (position.x + matchWidth))}px; height: {Math.abs(parentPosition.y + matchHeight / 2 - (position.y + matchHeight / 2)) + 2}px;"
              >
                <path
                  d="M {position.x + matchWidth - Math.min(position.x + matchWidth, parentPosition.x)} {position.y + matchHeight / 2 - Math.min(position.y + matchHeight / 2, parentPosition.y + matchHeight / 2)} 
                      L {parentPosition.x - Math.min(position.x + matchWidth, parentPosition.x)} {parentPosition.y + matchHeight / 2 - Math.min(position.y + matchHeight / 2, parentPosition.y + matchHeight / 2)}"
                  stroke="#6B7280"
                  stroke-width="2"
                  fill="none"
                  marker-end="url(#arrowhead)"
                />
                <defs>
                  <marker
                    id="arrowhead"
                    marker-width="10"
                    marker-height="7"
                    ref-x="9"
                    ref-y="3.5"
                    orient="auto"
                  >
                    <polygon
                      points="0 0, 10 3.5, 0 7"
                      fill="#6B7280"
                    />
                  </marker>
                </defs>
              </svg>
            {/if}
          {/if}
        {/each}
      </div>
    </div>
  {/if}
</div>

<style>
  .tournament-bracket-container {
    width: 100%;
    height: 100%;
  }

  .bracket-controls {
    display: flex;
    justify-content: center;
    padding: 1rem;
  }

  .bracket-container {
    background: #f8fafc;
  }

  .bracket-content {
    transition: transform 0.2s ease;
  }
</style>
