// srcs/services/frontend/src-svelte/components/MultiPlayerPong.svelte
<!--
  Multiplayer Pong game component for tournament matches.
  Handles real-time communication via Socket.IO.
-->

<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import SocketIOService from '../shared/services/socketIOService';
  import { _ } from 'svelte-i18n';

  export let roomId: string;
  export let playerSide: 'left' | 'right';

  let canvasRef: HTMLCanvasElement;
  let socketService: SocketIOService | null = null;
  let gameState = {
    leftPaddle: { y: 200 },
    rightPaddle: { y: 200 },
    ball: { x: 400, y: 200, dx: 5, dy: 3 },
    leftScore: 0,
    rightScore: 0,
    status: 'ready' as 'ready' | 'playing' | 'paused' | 'finished',
    winner: undefined as 'left' | 'right' | undefined
  };
  let connected = false;
  let keys = new Set<string>();

  onMount(() => {
    // Parse roomId format: "tournament-{id}-match-{matchId}" (e.g., "tournament-72-match-75")
    const match = roomId.match(/tournament-(\d+)-match-(\d+)/);
    if (!match || match.length < 3) {
      console.error('❌ Invalid roomId format:', roomId);
      return;
    }
    
    const tournamentId = match[1];
    const matchId = match[2];
    // Generate unique userId for each connection to avoid conflicts
    const userId = `player_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    
    console.log('Connecting to Socket.IO server for room:', roomId);
    console.log('🔍 Parsed tournamentId:', tournamentId, 'matchId:', matchId);
    
    socketService = new SocketIOService();

    // Set up event handlers
    socketService.setEventHandlers({
      onConnected: (data) => {
        console.log('Socket.IO connected:', data);
        setConnected(true);
      },
      onDisconnected: () => {
        console.log('Socket.IO disconnected');
        setConnected(false);
      },
      onGameState: (data) => {
        console.log('Received game state:', data);
        setGameState(data);
      },
      onGameStart: () => {
        console.log('Game started!');
        setGameState(prev => ({ ...prev, status: 'playing' }));
      },
      onGameEnd: (data) => {
        console.log('Game ended:', data);
        setGameState(prev => ({ 
          ...prev, 
          status: 'finished', 
          winner: data.winner,
          leftScore: data.leftScore,
          rightScore: data.rightScore
        }));
      },
      onError: (error) => {
        console.error('Socket.IO error:', error);
      }
    });

    // Connect to the room
    socketService.connectToRoom(roomId, userId);

    // Set up keyboard controls
    const handleKeyDown = (event: KeyboardEvent) => {
      keys.add(event.key.toLowerCase());
      handleMovement();
    };

    const handleKeyUp = (event: KeyboardEvent) => {
      keys.delete(event.key.toLowerCase());
      handleMovement();
    };

    const handleMovement = () => {
      if (!socketService || !connected) return;

      const movement = getMovementFromKeys();
      if (movement !== 0) {
        socketService.sendPaddleMovement(movement);
      }
    };

    const getMovementFromKeys = () => {
      if (playerSide === 'left') {
        if (keys.has('w') || keys.has('arrowup')) return -1;
        if (keys.has('s') || keys.has('arrowdown')) return 1;
      } else {
        if (keys.has('w') || keys.has('arrowup')) return -1;
        if (keys.has('s') || keys.has('arrowdown')) return 1;
      }
      return 0;
    };

    // Add event listeners
    window.addEventListener('keydown', handleKeyDown);
    window.addEventListener('keyup', handleKeyUp);

    // Cleanup function
    return () => {
      window.removeEventListener('keydown', handleKeyDown);
      window.removeEventListener('keyup', handleKeyUp);
      if (socketService) {
        socketService.disconnect();
      }
    };
  });

  onDestroy(() => {
    if (socketService) {
      socketService.disconnect();
    }
  });

  /**
   * Start the game
   */
  const startGame = () => {
    if (socketService && connected) {
      socketService.startGame();
    }
  };

  /**
   * Pause the game
   */
  const pauseGame = () => {
    if (socketService && connected) {
      socketService.pauseGame();
    }
  };

  /**
   * Reset the game
   */
  const resetGame = () => {
    if (socketService && connected) {
      socketService.resetGame();
    }
  };
</script>

<div class="flex flex-col items-center" data-testid="multiplayer-game-container">
  <h2 class="text-2xl mb-4">{$_('label.multiplayer')} - {$_('label.room')}: {roomId}</h2>
  
  <!-- Connection Status -->
  <div class="mb-4 flex items-center space-x-2">
    <div class="w-3 h-3 rounded-full {connected ? 'bg-green-500' : 'bg-red-500'}"></div>
    <span class="text-sm {connected ? 'text-green-600' : 'text-red-600'}">
      {connected ? $_('label.connected') : $_('label.disconnected')}
    </span>
  </div>
  
  <div class="mb-4 flex justify-center space-x-8">
    <div class="text-center">
      <div class="text-2xl font-bold text-blue-600">{gameState.leftScore}</div>
      <div class="text-sm text-gray-600">
        {playerSide === 'left' ? $_('label.you') : $_('label.opponent')}
      </div>
    </div>
    <div class="text-center">
      <div class="text-2xl font-bold text-red-600">{gameState.rightScore}</div>
      <div class="text-sm text-gray-600">
        {playerSide === 'right' ? $_('label.you') : $_('label.opponent')}
      </div>
    </div>
  </div>

  <div class="relative">
    <canvas
      bind:this={canvasRef}
      width={800}
      height={400}
      class="border-2 border-gray-300 rounded-lg bg-black"
    ></canvas>
    
    {#if gameState.status === 'paused'}
      <div class="absolute inset-0 flex items-center justify-center bg-black bg-opacity-50 rounded-lg">
        <div class="text-white text-xl font-bold">{$_('label.paused')}</div>
      </div>
    {/if}
    
    {#if gameState.status === 'finished'}
      <div class="absolute inset-0 flex items-center justify-center bg-black bg-opacity-50 rounded-lg">
        <div class="text-white text-xl font-bold">
          {$_('label.gameover')}! {$_('label.winner')}: {gameState.winner === playerSide ? $_('label.you') : $_('label.opponent')}
        </div>
      </div>
    {/if}
  </div>

  <div class="mt-4 flex space-x-4">
    <button
      on:click={startGame}
      disabled={gameState.status === 'playing' || !connected}
      class="px-4 py-2 bg-green-600 text-white rounded hover:bg-green-700 disabled:bg-gray-400 disabled:cursor-not-allowed"
    >
      {$_('button.startgame')}
    </button>
    
    <button
      on:click={pauseGame}
      disabled={gameState.status !== 'playing' || !connected}
      class="px-4 py-2 bg-yellow-600 text-white rounded hover:bg-yellow-700 disabled:bg-gray-400 disabled:cursor-not-allowed"
    >
      {$_('button.pause')}
    </button>
    
    <button
      on:click={resetGame}
      disabled={!connected}
      class="px-4 py-2 bg-red-600 text-white rounded hover:bg-red-700 disabled:bg-gray-400 disabled:cursor-not-allowed"
    >
      {$_('button.reset')}
    </button>
  </div>

  <div class="mt-4 text-sm text-gray-600 text-center">
    <p>{$_('instruction.player')}: {$_('instruction.wskeys')}</p>
    <p>{$_('instruction.space')}: {$_('instruction.startpause')}</p>
  </div>
</div>

// srcs/services/frontend/src/components/MultiPlayerPong.tsx
import React, { useEffect, useRef, useState } from 'react';
import SocketIOService from '../services/socketIOService';

interface MultiplayerPongProps {
  roomId: string;
  playerSide: 'left' | 'right';
}

export const MultiplayerPong: React.FC<MultiplayerPongProps> = ({ 
  roomId, 
  playerSide 
}) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const socketServiceRef = useRef<SocketIOService | null>(null);
  const [gameState, setGameState] = useState({
    leftPaddle: { y: 200 },
    rightPaddle: { y: 200 },
    ball: { x: 400, y: 200, dx: 5, dy: 3 },
    leftScore: 0,
    rightScore: 0,
    status: 'ready' as 'ready' | 'playing' | 'paused' | 'finished',
    winner: undefined as 'left' | 'right' | undefined
  });
  const [connected, setConnected] = useState(false);
  const [keys, setKeys] = useState<Set<string>>(new Set());

  // Connect to Socket.IO server
  useEffect(() => {
    // Parse roomId format: "tournamentId-matchId" (e.g., "14-4")
    const [tournamentId, matchId] = roomId.split('-');
    // Generate unique userId for each connection to avoid conflicts
    const userId = `player_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    
    console.log('Connecting to Socket.IO server for room:', roomId);
    
    const socketService = new SocketIOService();
    socketServiceRef.current = socketService;

    // Set up event handlers
    socketService.setEventHandlers({
      onConnected: (data) => {
        console.log('Socket.IO connected:', data);
        setConnected(true);
      },
      onPlayerJoined: (data) => {
        console.log('Player joined:', data.message);
      },
      onPlayerLeft: (data) => {
        console.log('Player left:', data.message);
      },
      onPlayerReady: (data) => {
        console.log('Player ready:', data);
      },
      onGameStart: (data) => {
        console.log('🎮 Game start event received:', data);
        // Update status based on server's roomState
        const serverStatus = data.roomState?.status === 'ready' ? 'playing' : data.roomState?.status || 'playing';
        setGameState(prev => ({ ...prev, status: serverStatus }));
        console.log('🎮 Game state updated to:', serverStatus);
      },
      onGamePlaying: (data) => {
        console.log('🎮 Game playing event received:', data);
        
        // Update status and initialize game data from server
        const serverStatus = data.roomState?.status || 'playing';
        const gameData = data.gameState || {};
        
        setGameState(prev => {
          const safePrev = prev || {};
          return {
            leftPaddle: gameData.leftPaddle || safePrev.leftPaddle || { y: 200 },
            rightPaddle: gameData.rightPaddle || safePrev.rightPaddle || { y: 200 },
            ball: gameData.ball || safePrev.ball || { x: 400, y: 200, dx: 5, dy: 3 },
            leftScore: typeof gameData.leftScore === 'number' ? gameData.leftScore : (safePrev.leftScore || 0),
            rightScore: typeof gameData.rightScore === 'number' ? gameData.rightScore : (safePrev.rightScore || 0),
            status: serverStatus,
            winner: safePrev.winner
          };
        });
        
        console.log('🎮 Game state updated to:', serverStatus, 'with initial game data:', gameData);
      },
      onGameStateUpdate: (data) => {
        console.log('Game state update:', data);
        console.log('Game state update data.gameState:', data.gameState);
        console.log('Game state update data.gameState.type:', data.gameState?.type);
        
        // Check if this is a paddle move message
        if (data.gameState && data.gameState.type === 'paddle_move') {
          const paddleMove = data.gameState;
          console.log('Paddle move received in onGameStateUpdate:', paddleMove);
          
          setGameState(prev => {
            const safePrev = prev || {};
            const newState = {
              leftPaddle: safePrev.leftPaddle || { y: 200 },
              rightPaddle: safePrev.rightPaddle || { y: 200 },
              ball: safePrev.ball || { x: 400, y: 200, dx: 5, dy: 3 },
              leftScore: safePrev.leftScore || 0,
              rightScore: safePrev.rightScore || 0,
              status: safePrev.status || 'ready',
              winner: safePrev.winner
            };
            
            // Update the appropriate paddle position
            if (paddleMove.player === 'left' && typeof paddleMove.y === 'number') {
              newState.leftPaddle = { y: paddleMove.y };
              console.log('Updated left paddle to y:', paddleMove.y);
            } else if (paddleMove.player === 'right' && typeof paddleMove.y === 'number') {
              newState.rightPaddle = { y: paddleMove.y };
              console.log('Updated right paddle to y:', paddleMove.y);
            }
            
            return newState;
          });
          return;
        }
        
        // Handle full game state updates
        const gameData = data.gameState || data.roomState?.gameData || data;
        
        setGameState(prev => ({
          ...prev,
          ...gameData,
          // Ensure paddles and ball have proper structure with defaults
          leftPaddle: gameData?.leftPaddle || prev.leftPaddle || { y: 200 },
          rightPaddle: gameData?.rightPaddle || prev.rightPaddle || { y: 200 },
          ball: gameData?.ball || prev.ball || { x: 400, y: 200, dx: 5, dy: 3 },
          leftScore: gameData?.leftScore !== undefined ? gameData.leftScore : prev.leftScore,
          rightScore: gameData?.rightScore !== undefined ? gameData.rightScore : prev.rightScore,
          // Keep current status unless explicitly provided
          status: gameData?.status || prev.status
        }));
      },
      onGameEnd: (data) => {
        console.log('Game end:', data);
        setGameState(prev => ({
          ...prev,
          status: 'finished',
          winner: data.gameResult.winner,
          leftScore: data.gameResult.leftScore,
          rightScore: data.gameResult.rightScore
        }));
      },
      onPong: () => {
        // Handle pong response
      },
      onDisconnect: (reason) => {
        console.log('Socket.IO disconnected:', reason);
        setConnected(false);
      },
      onError: (error) => {
        console.error('Socket.IO error:', error);
        setConnected(false);
      }
    });

    // Connect to server
    socketService.connect(parseInt(tournamentId), parseInt(matchId), userId)
      .then(() => {
        console.log('Socket.IO connection established');
      })
      .catch((error) => {
        console.error('Failed to connect to Socket.IO:', error);
        setConnected(false);
      });

    return () => {
      socketService.disconnect();
    };
  }, [roomId]);

  // Keyboard input handling
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      setKeys(prev => new Set([...prev, e.key.toLowerCase()]));
    };

    const handleKeyUp = (e: KeyboardEvent) => {
      setKeys(prev => {
        const newKeys = new Set(prev);
        newKeys.delete(e.key.toLowerCase());
        return newKeys;
      });
    };

    window.addEventListener('keydown', handleKeyDown);
    window.addEventListener('keyup', handleKeyUp);

    return () => {
      window.removeEventListener('keydown', handleKeyDown);
      window.removeEventListener('keyup', handleKeyUp);
    };
  }, []);

  // Paddle movement handling
  useEffect(() => {
    if (!connected || !socketServiceRef.current) return;

    // Only allow paddle movement when game is playing
    if (gameState.status !== 'playing') return;

    const paddleSpeed = 8;
    const keysToCheck = playerSide === 'left' ? ['w', 's'] : ['arrowup', 'arrowdown'];
    
    keysToCheck.forEach(key => {
      if (keys.has(key)) {
        // Add comprehensive defensive checks for paddle existence
        const safeGameState = gameState || {};
        const leftPaddle = (safeGameState.leftPaddle && typeof safeGameState.leftPaddle === 'object') 
          ? safeGameState.leftPaddle 
          : { y: 200 };
        const rightPaddle = (safeGameState.rightPaddle && typeof safeGameState.rightPaddle === 'object') 
          ? safeGameState.rightPaddle 
          : { y: 200 };
        const currentY = playerSide === 'left' ? leftPaddle.y : rightPaddle.y;
        let newY = typeof currentY === 'number' ? currentY : 200;
        
        if ((key === 'w' || key === 'arrowup') && newY > 0) {
          newY -= paddleSpeed;
        } else if ((key === 's' || key === 'arrowdown') && newY < 300) {
          newY += paddleSpeed;
        }
        
        // Update local game state safely
        setGameState(prev => {
          const safePrev = prev || {};
          return {
            leftPaddle: safePrev.leftPaddle || { y: 200 },
            rightPaddle: safePrev.rightPaddle || { y: 200 },
            ball: safePrev.ball || { x: 400, y: 200, dx: 5, dy: 3 },
            leftScore: safePrev.leftScore || 0,
            rightScore: safePrev.rightScore || 0,
            status: safePrev.status || 'ready',
            winner: safePrev.winner,
            [playerSide === 'left' ? 'leftPaddle' : 'rightPaddle']: { y: newY }
          };
        });

        // Send paddle position to server via Socket.IO
        if (socketServiceRef.current && socketServiceRef.current.isConnected()) {
          socketServiceRef.current.sendGameStateUpdate({
            type: 'paddle_move',
            player: playerSide,
            y: newY
          });
        }
      }
    });
  }, [keys, connected, playerSide, gameState, gameState.status]);

  // Rendering
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const renderLoop = () => {
      // Don't render if game state is not properly initialized
      if (!gameState || typeof gameState !== 'object') {
        console.log('Game state not initialized, skipping render');
        return;
      }
      
      // Debug logging
      console.log('Rendering with gameState:', gameState);
      // Clear canvas
      ctx.fillStyle = '#000';
      ctx.fillRect(0, 0, 800, 400);

      // Add comprehensive defensive checks for game state
      const safeGameState = gameState || {};
      
      // Ensure paddles have y property
      let leftPaddle = { y: 200 };
      let rightPaddle = { y: 200 };
      
      if (safeGameState.leftPaddle && typeof safeGameState.leftPaddle === 'object' && typeof safeGameState.leftPaddle.y === 'number') {
        leftPaddle = { y: safeGameState.leftPaddle.y };
      }
      
      if (safeGameState.rightPaddle && typeof safeGameState.rightPaddle === 'object' && typeof safeGameState.rightPaddle.y === 'number') {
        rightPaddle = { y: safeGameState.rightPaddle.y };
      }
      
      // Ensure ball has x, y properties
      let ball = { x: 400, y: 200, dx: 5, dy: 3 };
      if (safeGameState.ball && typeof safeGameState.ball === 'object') {
        ball = {
          x: typeof safeGameState.ball.x === 'number' ? safeGameState.ball.x : 400,
          y: typeof safeGameState.ball.y === 'number' ? safeGameState.ball.y : 200,
          dx: typeof safeGameState.ball.dx === 'number' ? safeGameState.ball.dx : 5,
          dy: typeof safeGameState.ball.dy === 'number' ? safeGameState.ball.dy : 3
        };
      }
      
      const leftScore = typeof safeGameState.leftScore === 'number' ? safeGameState.leftScore : 0;
      const rightScore = typeof safeGameState.rightScore === 'number' ? safeGameState.rightScore : 0;
      
      console.log('Safe rendering values:', { leftPaddle, rightPaddle, ball, leftScore, rightScore });

      // Draw paddles
      ctx.fillStyle = '#fff';
      ctx.fillRect(10, leftPaddle.y, 10, 100);
      ctx.fillRect(780, rightPaddle.y, 10, 100);

      // Draw ball
      ctx.beginPath();
      ctx.arc(ball.x, ball.y, 5, 0, 2 * Math.PI);
      ctx.fillStyle = '#fff';
      ctx.fill();

      // Draw center line
      ctx.setLineDash([5, 15]);
      ctx.beginPath();
      ctx.moveTo(400, 0);
      ctx.lineTo(400, 400);
      ctx.strokeStyle = '#fff';
      ctx.stroke();

      // Draw scores
      ctx.font = '24px Arial';
      ctx.fillStyle = '#fff';
      ctx.fillText(leftScore.toString(), 200, 30);
      ctx.fillText(rightScore.toString(), 600, 30);
    };

    const interval = setInterval(renderLoop, 16);
    return () => clearInterval(interval);
  }, [gameState]);

  // Game control functions
  const handlePause = () => {
    if (socketServiceRef.current && socketServiceRef.current.isConnected()) {
      socketServiceRef.current.sendGameStateUpdate({
        type: 'game_pause'
      });
    }
  };

  const handleReset = () => {
    if (socketServiceRef.current && socketServiceRef.current.isConnected()) {
      socketServiceRef.current.sendGameStateUpdate({
        type: 'game_reset'
      });
    }
  };

  // Sends a 'player_ready' message to the server when the Start button is clicked.
  // This is used to signal that the player is ready to begin the multiplayer game.
  const handleStart = () => {
    if (socketServiceRef.current && socketServiceRef.current.isConnected()) {
      socketServiceRef.current.sendPlayerReady(true);
    }
  };

  return (
    <div className="flex flex-col items-center">
      <h2 className="text-2xl mb-4">Multiplayer Pong</h2>
      <div className="mb-4">
        <span className={`px-4 py-2 rounded ${connected ? 'bg-green-600' : 'bg-red-600'}`}>
          {connected ? 'Connected' : 'Disconnected'}
        </span>
      </div>
      
      {/* Game Controls */}
      <div className="mb-4 flex gap-2">
        {/* Start button: Notifies the server that this player is ready to start */}
        <button 
          onClick={handleStart}
          className="px-4 py-2 bg-green-600 text-white rounded hover:bg-green-700"
        >
          Start
        </button>
        <button 
          onClick={handlePause}
          className="px-4 py-2 bg-yellow-600 text-white rounded hover:bg-yellow-700"
        >
          Pause
        </button>
        <button 
          onClick={handleReset}
          className="px-4 py-2 bg-red-600 text-white rounded hover:bg-red-700"
        >
          Reset
        </button>
      </div>
      
      {/* Game Status */}
      {/*
        Displays the current game status. The text is chosen to match Cypress E2E test expectations:
        - 'Initial' or 'Ready' for the ready state
        - 'Started' or 'Playing' for the playing state
        - 'Stopped' or 'Paused' for the paused state
      */}
      <div data-testid="game-status" className="mb-2 text-sm">
        {gameState.status === 'ready' && 'Initial / Ready'}
        {gameState.status === 'playing' && 'Started / Playing'}
        {gameState.status === 'paused' && 'Stopped / Paused'}
        {gameState.status === 'finished' && 'Game Over'}
      </div>
      
      {/* Game End Message */}
      {gameState.status === 'finished' && gameState.winner && (
        <div className="mb-4 p-4 bg-green-600 text-white rounded-lg text-center">
          <h3 className="text-xl font-bold mb-2">Game Over!</h3>
          <p className="text-lg">
            {gameState.winner === 'left' ? 'Left Player' : 'Right Player'} wins!
          </p>
          <p className="text-sm mt-2">Final Score: {gameState.leftScore} - {gameState.rightScore}</p>
        </div>
      )}
      <div className="mb-4 text-sm">
        <p>You are playing as: <strong>{playerSide.toUpperCase()}</strong></p>
        <p>{playerSide === 'left' ? 'W/S keys' : '↑/↓ keys'}</p>
      </div>
      <canvas
        ref={canvasRef}
        width={800}
        height={400}
        className="border border-white"
      />
    </div>
  );
};
